### ISSUE TITLE
봉사신청 완료시간이 보이도록 표시요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#10]
![2015-09-03 11 38 19](https://cloud.githubusercontent.com/assets/4696328/9649477/960c77cc-5230-11e5-946f-753e0c2023db.png)

봉사를 언제 신청했는지 알 수 있도록 우측에 봉사시간 신청완료시간을 표시해주셨으면 좋겠습니다.

**Comment by 10001if** [comment]
근데.. 이렇게 하면 방문일자랑 헷갈릴 수도 있겠네요.. 찾아뵙고 이야기를 여쭤보고 진행하고 싶습니다. ^^;

**Comment by aanoaa** [comment]
이미 표기되고 있습니다.
