### ISSUE TITLE
오전 봉사활동 시간 수정 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#100]
열린옷장 공식 점심시간이 12시 30부터 2시로 변경된 관계로
봉사자 오전 활동시간을 10시~12시 30분까지로 변경하고자 합니다. 

<img width="960" alt="2017-08-05 13 18 55" src="https://user-images.githubusercontent.com/17288038/28992779-bb549616-79e0-11e7-8be2-99db4fa67cb3.png">

봉사신청시 시간을 선택할 때 
**10시~ 12시 30분 (2시간 30분)
10시~18시 (6시간 30분)** 으로 수정 부탁드립니다.

**Comment by aanoaa** [comment]
봉사활동 시간과도 관련이 있는데,
프로그램을 수정하고 날짜관련이기 때문에 전반적으로 검토해봐야 합니다.

단순하게 프로그램 내부 시간은 그대로 두고 사용자가 선택하는 라벨만 변경하도록 하겠습니다.

    activity_from_date: 2017-08-09T10:00:00
    activity_to_date:   2017-08-09T13:00:00

-------------------------------

    activity_from_date: 2017-08-09T10:00:00
    activity_to_date:   2017-08-09T12:30:00

**Comment by pingpongworks** [comment]
네~

2017. 8. 9. 오후 3:43 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
