### ISSUE TITLE
봉사 승인 문자 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#101]
봉사 신청이 잘 되었다는 문자는 잘 가고 있는데, 
봉사 승인 후 봉사자에게 전달되던 문자가 언제부터인가 안 가고 있습니다. 
6월 20일경까지는 정상적이었던 걸 봉사자분한테 확인했으니까 
아마도 약 한달 전부터로 추정됩니다. 

봉사 승인 문자는 아래 예시와 같이 봉사신청을 취소할 수 있는 링크가 들어있는 문자입니다. 
최근에 봉사신청하고 연락없이 안 오시는 분들이 많아진 이유일 것 같습니다. 
정상적으로 문자가 갈 수 있도록 부탁드립니다. 

> 제목없음
[Web발신]
김소령님이 5월 29일 10~18시에 신청하신 봉사활동이 승인되었습니다.
신청한  봉사일에 방문할 수 없는 경우, 신청한 봉사활동을 취소하려면 다음의           http://volunteer.theopencloset.net/works/2281/cancel?phone=2844 을 눌러 취소해주세요. 봉사취소는 봉사 신청일 하루 전까지만 가능합니다. 봉사 신청 후 미방문하는 경우, 결원으로 인한 운영상의 어    려움이 발생합니다. 미방문시에는 꼭! 봉사신청을 취소해주세요.
봉사신청과 관련하여 추가적으로 문의사항이 있는 경우 02-6929-1020 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

**_한가지 궁금한 게 있습니다. 
봉사 신청 확인문자는 02-6929-1029 으로 발송되는데,  
승인 확인 문자는 02-6929-1020 으로 발송되고 있었습니다. 
봉사자분들이 헷갈릴 수 있을 거 같은데요, 
특별한 이유가 있는지요?_**

**Comment by aanoaa** [comment]
문자메세지 전송되고 있습니다.
발신번호 `0269291029` 으로 오늘(`2017-08-07`) 문자가 전송된 기록이 있습니다.
메세지에 전화번호가 `02-6929-1020` 으로 되어 있는데 왜 그랬는지 모릅니다.

> xxx님이 9월 3일 14~18시에 신청하신 봉사활동이 승인되었습니다.
> 
> 신청한 봉사일에 방문할 수 없는 경우, 신청한 봉사활동을 취소하려면 다음의 http://volunteer.theopencloset.net/works/xxxx/cancel?phone=xxxx 을 눌러 취소해주세요. 봉사취소는 봉사 신청일 하루 전까지만 가능합니다. 봉사 신청 후 미방문하는 경우, 결원으로 인한 운영상의 어려움이 발생합니다. 미방문시에는 꼭! 봉사신청을 취소해주세요.
> 
> 봉사신청과 관련하여 추가적으로 문의사항이 있는 경우 02-6929-1020 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

**Comment by pingpongworks** [comment]
기록상으로는 그렇군요. 현실에서는 문자전송이 되고 있지 않습니다^^;;
어제 오늘, 봉사자분들 몇 분께 확인했고, 제가 직접 봉사신청도 해보았습니다. 
다시 한번 확인 부탁드릴게요~

**Comment by aanoaa** [comment]
버그입니다.
수신자 번호 형식이 `01012345678` 이어야 하는데 `010-1234-5678` 으로 문자메세지를 보내려고 해서 발생한 문제입니다.

    ## [v0.3.3] - Thu, 08 Jun 2017 02:16:43 +0900
    ### Added
    - staff 의 봉사활동 목록을 /works 로 이관

이때부터 문제가 발생한 것 같습니다.

아까 확인한 승인메세지의 수신자번호는 `010-xxxx-xxx` 입니다.
잘못된 것 입니다. 수신자 번호에 `-` 가 들어가고 마지막 번호가 잘렸습니다.

시스템은 발송했지만 수신자 번호가 잘못되어서 메세지를 받지 못한 것 입니다.

봉사활동 프로그램에서 이와 같은 문제가 발생하고 있는지 문자메세지를 보내는 모든 부분을 확인해봐야 합니다.

**Comment by aanoaa** [comment]
- 신청
- 승인
- 위치안내

문자메세지를 보내는 부분은 위 3가지 입니다.
신청할때는 이문제가 처리되어있었고, 승인과 위치안내에서만 발생하고 있습니다.

**Comment by pingpongworks** [comment]
승인문자 테스트 완료하였습니다. 감사합니다^^
