### ISSUE TITLE
운영시간 변경에 따른 봉사활동 시간 변경

### ISSUE THREAD

**Issue by ghost** [opencloset/volunteer#102]
운영시간 변경에 따라 봉사활동 시간을 변경하고자 합니다.
9월 4일부터 건국대학교 사회봉사 과목을 듣는 학생들도 봉사를 신청할 예정입니다.
건국대학교에는 공식적으로 변경된 내용을 안내해 드렸습니다.
그래서 8월 안에는 반영되어야 하는 이슈입니다.

[기존]
오전 - 10시 ~ 13시 (3시간)
오후 - 14시 ~ 18시 (4시간)
종일 - 10시 ~ 18시 (7시간)

[변경]
오전 - 10시 ~ **12시 30분 (2시간 30분)**
오후 - 14시 ~ 18시 (4시간)
종일 - 10시 ~ 18시 **(6시간 30분)**

봉사신청서에는 반영이 된 것 같은데, 아직 반영이 되지 않은 곳에 여러 곳 있어서 남겨 놓습니다.

- 봉사 신청 목록
![01](https://user-images.githubusercontent.com/14110661/29236240-0039ab88-7f43-11e7-81da-f147a1b7ffd0.jpg)

- 구글 캘린더
![02](https://user-images.githubusercontent.com/14110661/29236243-0437ac58-7f43-11e7-9dd1-4b306c0272f3.jpg)

- 신청 후 문자 및 웹 페이지
여기에선 시간이 아니라 **4일에 신청하신**을 **9월 4일에 신청하신**으로 월까지 표시해 주셨으면 합니다.
![03](https://user-images.githubusercontent.com/14110661/29236245-0686d40c-7f43-11e7-8d46-f66adc0d0632.png)
![05](https://user-images.githubusercontent.com/14110661/29236355-7889489a-7f44-11e7-9314-ccdb10daf98b.png)

- 승인 후 문자
![04](https://user-images.githubusercontent.com/14110661/29236246-096d9430-7f43-11e7-8f60-581634dcb7b1.png)

**Comment by 10001if** [comment]
![2017-08-14 12 00 49](https://user-images.githubusercontent.com/4696328/29256836-40f67218-80e8-11e7-8d35-233a682def69.png)
https://volunteer.theopencloset.net/
이곳도 수정해야 합니다. 이미지를 다시 만들어 보내드리겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/volunteer/issues/100#issuecomment-321167737

> 봉사활동 시간과도 관련이 있는데,
> 프로그램을 수정하고 날짜관련이기 때문에 전반적으로 검토해봐야 합니다.
> 
> 단순하게 프로그램 내부 시간은 그대로 두고 사용자가 선택하는 라벨만 변경하도록 하겠습니다.
> 
> activity_from_date: 2017-08-09T10:00:00
> activity_to_date:   2017-08-09T13:00:00
> 
> activity_from_date: 2017-08-09T10:00:00
> activity_to_date:   2017-08-09T12:30:00

위처럼 라벨만 변경하는 걸로는 부족한가요?
3시간 신청하고 2시간 30분 인정받으면 문제가 있을 것 같다고 생각해서 최소한의 조치를 했습니다.

**Comment by 10001if** [comment]
@MoDoLEE 형석님 의견에 답 부탁할게요~

**Comment by ghost** [comment]
봉사자에게 혼선을 줄 수 있는 최소한의 부분만 수정하면 될 것 같습니다.
구글캘린더와 승인 후 문자에 표시되는 시간이 변경되어야 합니다.

**Comment by aanoaa** [comment]
한번에 여러건을 신청할 수 있게 되면서 `x월 x일` 대신에 `x일` 로 표시해달라고 요청받았습니다.

    1. 홍길동님이 4일, 11일, 18일에 신청하신 ...
    2. 홍길동님이 9월 4일, 9월 11일, 9월 18일에 신청하신 ...

다시 2번 으로 변경하도록 하겠습니다.

**Comment by aanoaa** [comment]
시간단위로 지원되던 봉사활동을 분단위까지 지원하도록 수정하고 배포하였습니다.
변경은 했지만 구글캘린더가 분단위까지 지원하는지는 모르겠습니다.
활동시간 10:00 ~ 12:30 으로 신청부터 승인까지 확인바랍니다.

**Comment by ghost** [comment]
신청 목록, 문자는 정상적으로 작동합니다.

큰 문제는 아니지만 구글캘린더에 기록되는 내용에 조금 문제가 있습니다.
10시 ~ 12시 30분은 정상적으로 기록되는데,

10시 ~ 18시를 신청하면 시간은 10시 ~ 11시로 기록되고 이름 옆에 06:00 pm이 기록됩니다.
![10to18](https://user-images.githubusercontent.com/14110661/29348520-600e654a-828f-11e7-8de1-22e5a5f1761b.png)

14시 ~ 18시를 신청하면 시간은 14시 ~ 12시로 기록되고 이름 옆에 06:00 pm이 기록됩니다.
![14to18](https://user-images.githubusercontent.com/14110661/29348522-61a54824-828f-11e7-8146-15d18b2e841d.png)

이 부분 수정과
@pingpongworks 님이 포스터에 있는 시간만 수정해 주시면 될 것 같습니다.
https://volunteer.theopencloset.net/

**Comment by aanoaa** [comment]
```
[Wed Aug 16 12:52:05 2017] [debug] QuickAdd: 이성일 on August 30 10:00am-12:30pm
[Wed Aug 16 12:54:52 2017] [debug] QuickAdd: 이성일 on August 31 10:00am-06:00pm
[Wed Aug 16 14:22:19 2017] [debug] QuickAdd: 이성일 on August 29 10:00am-06:00pm
[Wed Aug 16 14:23:03 2017] [debug] QuickAdd: 이성일 on August 29 10:00am-12:30pm
[Wed Aug 16 14:23:30 2017] [debug] QuickAdd: 이성일 on August 29 02:00pm-06:00pm
```

캘린더에선 지워졌지만 5번의 승인 이력을 발견했습니다.
구글캘린더의 [Events: quickAdd](https://developers.google.com/google-apps/calendar/v3/reference/events/quickAdd) 기능을 사용해서 넣고 있는데,
형식이 잘못된게 아닐까 합니다.

text 에 what, where, with, who, when 등의 내용을 넣으면 된다고 설명되어 있는데 정확하게 어떤 형식인지는 문서에 없습니다.
다만 시도해 볼 뿐입니다.

    이성일 from 10:00am to 12:30pm on August 30

처럼 시도해보겠습니다.

만약 이것도 의도한대로 동작하지 않는다면 `quickAdd` 대신에 [insert](https://developers.google.com/google-apps/calendar/v3/reference/events/insert) 를 대신 사용하도록 해야 하겠습니다.

**Comment by aanoaa** [comment]
홍길동 on from 10:00am to 12:30pm on August 29

날짜 및 시간은 제대로 들어갔는데 달력에 `홍길동 on` 이라고 표시됩니다.
오타니까 수정하면 될 것 같습니다.

**Comment by aanoaa** [comment]
홍길동 from 10:00am to 06:00pm on August 29

으로 quickAdd 를 통해서 달력에 이벤트를 넣었습니다.

--------------------------------------

![default](https://user-images.githubusercontent.com/170528/29349675-15e1003e-8296-11e7-8853-1569842f1663.png)

quickAdd 대신에 insert 를 사용하는 방식이 되어야 할 것 같습니다.

**Comment by aanoaa** [comment]
quickAdd 대신에 insert 를 사용해서 넣도록 하였습니다.

**Comment by 10001if** [comment]
이슈 우선순위에서 제거 하도록 하겠습니다.
