### ISSUE TITLE
홈페이지 자원봉사 모집 포스터 교체 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#103]
![- - _2017 08 18](https://user-images.githubusercontent.com/17288038/29449980-dab6edb8-8437-11e7-9dfc-6756a1de323e.png)

활동가능 시간, 고등학생 이상 신청가능 등
내용을 수정하였습니다. 
홈페이지에 자원봉사 신청시 뜨는 포스터, 교체해주세요~

Ai 파일이 혹시 필요할지도 몰라서 그건, 메일로 보내놓았습니다~

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
