### ISSUE TITLE
9월부터 봉사 신청 인원 조정 요청합니다

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#104]
9월 1일부터 
동시간대 3명 신청 가능하도록 조정 부탁드립니다. 

9월은 비수기도 성수기도 아닌 애매한 시기인지라
#99 에서 요청드렸던 인원 4명과 차이가 있습니다.

**Comment by aanoaa** [comment]
변경하였습니다.

**Comment by pingpongworks** [comment]
감사합니다~

2017. 9. 1. 오전 10:16 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
