### ISSUE TITLE
봉사자 제한 수 문의

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#106]
11월 11일(토)와 11월 19일(일)에 봉사자 신청자 수가 동시간대 5명입니다. 이과 관련해서 문의가 왔는데요. 현재 동시간 대 신청자 수가 4명인 것으로 알고 있는데, 초과되어 신청이 된 것으로 보입니다. 혹시 옷장지기 실수인지 확인 부탁드릴게요. 제한 인원 4명을 초과하여 봉사자가 방문하면 여유 인원이 생겨 봉사자 관리가 어려운 부분이 있기 때문입니다~

**Comment by aanoaa** [comment]
현재 봉사활동은 동시간에 최대 3명을 허용하고 있습니다.
내일 10시에 2명 신청 10시에 1명 승인이 되었다면 더이상 내일 10시에 신청을 할 수 없어야 합니다.
11/11일은 10 ~ 18 3명, 14 ~ 18 2명 입니다.
해서 14 ~ 18시가 5명이 되었습니다.(3명을 넘길 수 가 없는데)
프로그램의 버그인건지 탐구생활을 해봐야 합니다.

**Comment by 10001if** [comment]
마지막 이슈를 보니 #104 봉사자 제한이 3명이어서 저도 그렇게 이해하고 있었는데 4명인 날이 좀 있어서 인원을 조정했는지 알았네요~ 11월 3일, 4일, 6일이 모두 4명이었습니다~

**Comment by aanoaa** [comment]
프로그램 버그가 맞습니다.
오타가 있었습니다.

https://github.com/opencloset/volunteer/blob/develop/lib/OpenCloset/Volunteer/Controller/Work.pm#L522

**Comment by aanoaa** [comment]
이미 신청/승인 되어버린 것은 데이터를 건드린다고 될 문제가 아니라서 불편하시겠지만 봉사자 분이랑 연락을 취해서 해결해주세요.

해당 버그는 수정되었으니 앞으로는 설정한 인원이상 신청하지 못할 것입니다.

**Comment by 10001if** [comment]
네~ 이미 신청하신 건은 저희가 따로 연락을 드리도록 하겠습니다~ 버그 수정 감사드립니다.
