### ISSUE TITLE
다른 날 신청한 봉사가 같은 날로 등록되어 있음

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#107]
![default](https://user-images.githubusercontent.com/4696328/34137882-5f9436e8-e4b0-11e7-9535-3acf001df614.jpg)

그림처럼 1월 2일, 5일 신청자인데 5일에 두번에 걸쳐 등록되어 있습니다.

확인 요청드립니다.

**Comment by aanoaa** [comment]
신청한건 확인이 되는데 승인문자는 기록에 없네요.
어떻게 승인된거지..

승인문자를 발송하고 캘린더에 집어넣거든요.
승인문자 발송이력이 없는걸 보면 정상적인 접근은 아닌 것 같습니다.

**Comment by 10001if** [comment]
정상적인 접근이 아니라면, 우선 그냥 넘어가고 다음에 같은 상황이 다시 나타나면 말씀드리도록 할까요? 5일 신청건을 2일로 옮기는게 맞을까요?

**Comment by aanoaa** [comment]
죄송합니다.
올바른 조치는 아니지만 재발하면 그때 살펴볼게요.

**Comment by 10001if** [comment]
@aanoaa 아닙니다~ 저희도 빈번하게 발생한 건은 아니니 조금 더 지켜보고 이야기 드릴 상황이 생기면 다시 남기도록 하겠습니다~

**Comment by 10001if** [comment]
도움이 될까 하여 남깁니다. 근데 두 건 모두 정상적으로 승인한 건 맞다고 하네요. 담당자가 두 건을 모두 승인하자마자 캘린더에 동일한 날짜로 들어와서 이상하다 생각해 이야기 한 것이라고 합니다. 옷장지기는 정상적인 프로세스로 이용한 것으로 보입니다.
