### ISSUE TITLE
봉사 신청 가능 인원수 조정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#110]
동 시간대 2명만 신청가능하도록 조정 부탁드립니다.

**현재 동시간대 신청가능 인원**
오전 3명 / 오후 3명
종일 봉사자인 경우 3명

**변경 요청**
오전 2명 / 오후 2명
종일봉사자인 경우 2명

**Comment by pingpongworks** [comment]
이전에 @aanoaa 님에게 부탁했던 것과 같은 이슈라 assignees 걸었어요~

**Comment by aanoaa** [comment]
네 적용하였습니다.

**Comment by pingpongworks** [comment]
헉, 이렇게 빨리,,,감사합니다~

**Comment by aanoaa** [comment]
원래 번거로운 작업이었는데 그게 귀찮아서 지난번에 쉽게 바꿀 수 있도록 작업 했거든요
