### ISSUE TITLE
비수기, 봉사신청 가능 인원수 조정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#112]
동 시간대 1명만 신청가능하도록 조정 부탁드립니다.

[**현재 동시간대 신청가능 인원**]
오전 2명 / 오후 2명
종일 봉사자인 경우 2명

[**변경 요청**]
오전 1명 / 오후 1명
종일봉사자인 경우 1명

**Comment by aanoaa** [comment]
변경하였습니다.
