### ISSUE TITLE
봉사신청 가능 시간 변경

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#113]
운영시간 변경에 따라 봉사자 신청가능 시간도 변경이 필요합니다. 
아래와 같이 요청드립니다.
----------------------------------------------

**[월~금]**
9:00 - 12:00 (3시간)
12:00 - 16:00 (4시간)
17:00 - 20:00 (3시간)
9:00 - 16:00 (6시간) (12시-1시 점심시간)

**[토~일]**
9:00 - 12:00 (3시간)
12:00 - 17:00 (5시간)
9:00 - 17:00 (7시간) (12시-1시 점심시간)

------------------------------------------------
바로 내일부터 적용하게 되면 현재 신청들어와 있는 봉사자들과 시간 충돌이 있습니다. 
한달 뒤인 8월 16일 (금)부터 위 내역으로 적용되도록 부탁드립니다.

**Comment by aanoaa** [comment]
신청 가능한 시간대가 동적으로 계산되기 때문에 겹쳐도 괜찮습니다.

예로 모든 시간이 가능하고 14:00 시만 가능 슬롯이 없으면 14:00 포함된 모든 예약 시간대에는
봉사신청을 할 수 없습니다.

바뀐 시간대로 예를들면..

09:00 ~ 12:00 가능
17:00 ~ 20:00 가능

하게 됩니다.

---

주중과 주말을 구분하는 것이 좀 애매한데,
주말에는 18, 19, 20 시간대의 slot 을 0 으로 설정해두면 야간은 막을 수 있는데..

[월 ~ 일]
9:00 - 12:00 (3시간)
12:00 - 16:00 (4시간)
12:00 - 17:00 (5시간)
17:00 - 20:00 (3시간)
9:00 - 16:00 (6시간) (12시-1시 점심시간)
9:00 - 17:00 (7시간) (12시-1시 점심시간)

이렇게 선택지가 주어지면 아니되나요?
각 요일의 시간대별로 봉사자수를 조절할 수는 있는데,
기간을 요일별로 나누는 것은 애매합니다.

**Comment by aanoaa** [comment]
정해주세요 제가 제안드린 것처럼 다양한 시간대를 선택할 수 있게 하거나,
주중과 주말의 시간을 통일 하거나(야간빼고)

이런 상황을 고려해서 일별/시간별로 컨트롤 할 수 있게 했는데, 추가적인 예외 상황이라서
적용하기가 까다롭습니다.

**Comment by pingpongworks** [comment]
네~ 그럼 다음과 같이 다시 시간 정할게요.

9시-16시 _ 월-일 동일
17시-20시 _ 월-금 만

----------------------------------

[월~금]
9:00 - 12:00 (3시간)
12:00 - 16:00 (4시간)
9:00 - 16:00 (6시간) (12시-1시 점심시간)
17:00 - 20:00 (3시간)

[토~일]
9:00 - 12:00 (3시간)
12:00 - 16:00 (4시간)
9:00 - 16:00 (6시간) (12시-1시 점심시간)

**Comment by aanoaa** [comment]
적용하였습니다.
지금 슬롯이 1개이고 신청 해놓은 활동이 18:00 까지 걸쳐있기 때문에, 모든 시간대에 빈 공간이 없습니다.
테스트를 할 공간이 없어서 제가 봉사활동을 신청해보진 못했지만 의도한 대로 동작할 것으로 믿습니다.
내일 특정일의 신청을 취소하신 후에 테스트 해보시고 문제가 없다면 닫아주세요.

**Comment by pingpongworks** [comment]
확인해보겠습니다. 감사합니다^^

**Comment by pingpongworks** [comment]
토, 일 17:00~20:00 에는 슬롯을 0으로 설정해주신 것으로 알고 있었는데, 현재 봉사신청이 가능합니다. 
주말마다 옷장지기가 신청해서 신청이 들어올 수 없도록 막아야하는 것인가요? 
확인 부탁드립니다.

**Comment by aanoaa** [comment]
서비스 재시작이 제대로 안된건가..
특정일을 말씀해주시겠어요?
제가 테스트해보고 있는데 정상인 것 같습니다.

**Comment by aanoaa** [comment]
발견했습니다.
2019-09-07 날짜로 테스트해보면 재현되네요.

**Comment by aanoaa** [comment]
수정했습니다

**Comment by pingpongworks** [comment]
9월 8일은 17시~20시 시간 선택이 되지 않도록 제대로 설정되어 있는 거 같은데, 
9월 7일은 모든 시간이 신청할 수 없게 되어있습니다. 이유가 있을까요?

**Comment by aanoaa** [comment]
12 ~ 16 시에 한건 신청되었고 승인되었기 때문인 것 같습니다.
가능인원이 1명이고 12시는 모든 스케쥴에 포함되는 영역이라서 영향을 받는 구간에서 가용인원이 0명으로 계산된 것 입니다.

**Comment by pingpongworks** [comment]
네~ 그럼 정상적으로 주말 17시 이후 막힌거죠? 이슈 닫을게요~

**Comment by pingpongworks** [comment]
현재 봉사신청에 오류 증상이 있습니다. 

1) 9시-12시 신청자가 있을 경우,  12시-16시 신청이 안됨
2) 12시-16시 신청자가 있을 경우, 9시-12시 신청이 안됨

확인 부탁드립니다.

**Comment by aanoaa** [comment]
12 가 겹쳐서 그러합니다 중복을 피하려면 다른 시간계획을 세워야 합니다

12까지가 12:59 를 뜻하는 건지 12:00 까지를 뜻하는건지에 따라 다르게 해석될 수 있네요

현재 시스템에서는 12:59 입니다

**Comment by aanoaa** [comment]
9-12(4시간), 13-16(4시간) 이래야 하나요?

**Comment by pingpongworks** [comment]
[월~금]
9:00 - 11:59 (3시간)
12:00 - 15:59 (4시간)
9:00 - 15:59 (6시간) (12시-1시 점심시간)
17:00 - 19:59 (3시간)

[토~일]
9:00 - 11:59 (3시간)
12:00 - 15:59 (4시간)
9:00 - 15:59 (6시간) (12시-1시 점심시간)

예전에 요청드렸던 시간에서 1분씩 뺏습니다.

**Comment by aanoaa** [comment]
제가 드린 설명은 맞는 말이지만, 기존의 계산 방식이 맞습니다.
9-12 라고 하면 9시 정각부터 12시 정각까지 해서 3시간
그리고 이게 더 이해하기 쉽습니다.

지금처럼 보여주고 시스템에서 끝나는 시간을 하나 빼주면 됩니다.
그리 패치하도록 하겠습니다.

**Comment by aanoaa** [comment]
지금 시간 기준으로 15일 같은 경우에는 9-12 에 하나의 slot 이 비어야 하는데 그러지 않았습니다.
지금 패치해서 적용하였습니다. 06e390f5d07744d00ed1374d3875d7bc285b8deb

**Comment by pingpongworks** [comment]
네~

**Comment by aanoaa** [comment]
이거 적용되었습니다.
확인해보시고 이상이 있다면 다시 열어주세요.
