### ISSUE TITLE
봉사신청 가능 시간 변경_6시간 봉사시간 삭제

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#114]
[월~금]
    9:00 - 12:00 (3시간)
    12:00 - 16:00 (4시간)
    17:00 - 20:00 (3시간)

    [토~일]
    9:00 - 12:00 (3시간)
    12:00 - 16:00 (4시간)

위와 같이 봉사신청 가능시간 수정 부탁드립니다.
기존에서 9시-16시(6시간) 봉사가 삭제되는 것입니다. 
**또한 1일 1인 1타임만 선택할 수 있도록 해주세요.**

**Comment by aanoaa** [comment]
특정인에 대해 하루 한건만 적용시키기는 어렵습니다.
사용자 인증을 하는 서비스가 아니라서요.
관리자가 승인해야 하는 시스템이기 때문에 휴먼 필터링이 필요합니다.

**Comment by aanoaa** [comment]
09-16 시간대에 봉사 신청을 할 수 없도록 적용했습니다.

**Comment by pingpongworks** [comment]
<img width="637" alt="스크린샷 2020-02-28 오전 9 09 36" src="https://user-images.githubusercontent.com/17288038/75498338-37c43600-5a0a-11ea-8d92-bbcfc12f70a7.png">

-----------------
빨간 글씨 부분을 다음과 같이 수정해주세요. 

    봉사 신청은 복수로 가능하나 1일 1회만 가능합니다. 1회 신청시 추가로 다른 신청일과 시간을 입력해주세요. 다만, 예약이 완료된 시간은 선택이 불가능합니다. 예약가능한 활동시간만 선택해주세요.

추가 문구 삽입으로 1일 1회 신청 유도하려고 합니다. 문구수정 부탁드립니다.
수정하는 김에 '목록에서 항목을 선택해주세요'는 삭제해주세요. 없어도 될 거 같습니다.
