### ISSUE TITLE
봉사신청 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#116]
<img width="707" alt="스크린샷 2020-03-25 오후 8 33 11" src="https://user-images.githubusercontent.com/17288038/77532301-f5422c00-6ed7-11ea-8b69-c7ec30a65158.png">
<img width="750" alt="스크린샷 2020-03-25 오후 8 33 00" src="https://user-images.githubusercontent.com/17288038/77532311-fa06e000-6ed7-11ea-9e42-8f77a6c73e7e.png">
4월 3일 12시 ~16시
4월 8일 12시 ~16시
봉사시간이 분명히 비어있는데 신청하려고 하면 시간이 뜨지 않습니다.
확인 부탁합니다.

**Comment by aanoaa** [comment]
프로그램의 버그가 맞습니다.
수정해서 배포했습니다.

**Comment by pingpongworks** [comment]
확인했어요. 감사합니다~
