### ISSUE TITLE
코로나 상황에 맞춘 봉사관리 페이지 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#120]
코로나 이후로 1365 봉사승인사이트에서 모든 봉사신청은 1365 관리하에 신청하도록 하고 단체 홈페이지에 직접 신청하지 않도록 제한하고 있습니다.  봉사자가 직접 신청하는 것이 아니라서 스태프가 관리하기에 편리한 방향으로 수지니 봉사페이지 수정을 요청드립니다. 

1.  봉사자 입력 정보 간소화
**- 이름**
**- 전화번호**
**- 봉사활동 날짜**
3가지만 필수 입력값으로 수정해주세요.

<img width="734" alt="봉사 수정" src="https://user-images.githubusercontent.com/17288038/100223924-78cc8500-2f5f-11eb-8deb-920b5126a040.png">
<img width="734" alt="봉사신청2" src="https://user-images.githubusercontent.com/17288038/100223941-7ec26600-2f5f-11eb-892f-7af2b7384eb6.png">
(빨간박스 내용만 남기고 모두 삭제해주세요)

2. 봉사활동 날짜, 시간선택 수정
**09시 ~ 12시 / 3시간**
**14시 ~ 17시 / 3시간**
**17시 ~ 20시 / 3시간**
모든 요일 동일합니다.

3. 스태프가 봉사자 정보 입력 후 발송되는 문자 수정

1>입력하자마자 발송되는 문자
```
[열린옷장 봉사 안내]
안녕하세요. 000님이 1월 1일, 2월 2일, 3월 3일에 신청하신 자원봉사신청이 정상적으로 접수되었습니다. 
아래 필수확인사항 확인하시고 활동이 불가능한 경우 미리 연락 부탁드립니다. 

#필수확인사항
* 봉사활동 시작시간 이후 10분까지 미방문시 활동 임의취소
* 예고없이 미방문시 이후 예정된 활동에 대해 모두 취소처리
* 활동이 어려운 경우 전화(02-6929-1020) / 열린옷장 카톡채널로 미리 연락
```

2>봉사활동 전일 오후 3시 
```
[열린옷장 봉사안내]
000님 안녕하세요. 내일은 열린옷장과 함께 봉사활동하는 날인 것 잊지 않으셨죠? 건강한 모습으로 뵙겠습니다.

* 활동장소 : 건대앞 열린옷장 5층으로 방문해주세요. (서울시 광진구 아차산로 213 502호)
* 마스크 착용 필수 / 방문시 체온측정합니다. 

```

**Comment by aanoaa** [comment]
지금의 절차는 신청 -> 승인의 단계를 거치는데, staff 이 직접입력하는 거라면 신청하자마자 승인이 되어야 하는 건가요?

신청 후 문자/승인 후 문자가 구별되었는데 승인 후 문자는 없어져야 하겠네요.

**Comment by aanoaa** [comment]
입력 폼 및 SMS 변경했습니다.
테스트 부탁드립니다.

**Comment by pingpongworks** [comment]
<img width="734" alt="스크린샷 2020-11-28 오후 6 43 55" src="https://user-images.githubusercontent.com/17288038/100499029-bae90700-31a9-11eb-83c1-30800d2435dc.png">

- 테스트 결과 신청서에 필요한 항목만 남고 정리가 잘 되었습니다.
- 신청 후 승인단계 없이 바로 봉사안내 문자도 잘 오고 있습니다.
- 그런데 신청한 내역이 캘린더에 뜨지 않습니다. 원래 승인을 하면 캘린더에 뜨게되는데 승인단계가 없어져서 그런 거 같습니다.  봉사신청내역이 캘린더에 떠야 구성원들이 모두 봉사신청현황을 알 수 있고, 봉사자가 참석하지 않은 경우 담당자에게 전달할 수 있습니다. 캘린더에 뜨도록 부탁드립니다.

**Comment by aanoaa** [comment]
구글 캘린더에 스케쥴이 등록되도록 수정하였습니다.

**Comment by pingpongworks** [comment]
네 확인했습니다 감사합니다.

**Comment by pingpongworks** [comment]
<img width="705" alt="스크린샷 2020-11-30 오전 7 42 14" src="https://user-images.githubusercontent.com/17288038/100555569-adce3400-32df-11eb-9d01-042a8cea2b43.png">

같은날 두번 이상 신청할 수 있게 수정 요청드립니다.

**Comment by aanoaa** [comment]
같은 날 여러번 신청할 수 있도록 변경했습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다. 이제 진짜 이슈 닫을게요~
