### ISSUE TITLE
자원봉사 신청을 제한함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#124]
현재 코로나 때문에 자원봉사 신청을 받고 있지 않은데, 
포털에서 `열린옷장 자원봉사`를 검색해서 신청페이지를 찾은 후
직접 들어가 신청하는 경우가 종종 있습니다. 

https://volunteer.theopencloset.net/

신청페이지를 열었을 때 모집하고 있지 않음을 알리는 다음의 안내글 만 뜨고
신청이 가능한 탭은 보이지 않도록 수정 부탁드립니다. 

    코로나19 거리두기로 인해 
    현재 자원봉사자 모집을 하고 있지 않습니다.
    상황이 좋아진 후 건강하게 뵙겠습니다.

**Comment by keedi** [comment]
사용자가 동적으로 처리할 수 있게하는 부분은 별도의 이슈로 처리하겠습니다.

우선 소스 수정없이, 운영자가 신청을 열고 닫을 수 있게 처리하겠습니다.

**Comment by keedi** [comment]
서버는 임시 작업으로 대응했기 때문에 릴리즈 후 신 버전으로 반영하면 됩니다.
