### ISSUE TITLE
방문화면에서 1365 승인과 대기중인 상태를 구분해서 보기

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#13]
![2015-09-09 2 10 52](https://cloud.githubusercontent.com/assets/4696328/9753981/0da61cf2-56ff-11e5-9a4e-770acbbb3aff.png)

봉사활동 신청, 승인과 달리 방문의 경우에는 1365를 승인했는지 여부를 확인하는 과정이 필요합니다. 
하지만 최근 날짜별로 뜨기 때문에 일주일동안 쌓이는 인원도 꽤 많을 것 같습니다.

그래서 위 그림처럼 승인대기중인 인원만 최근 날짜 순으로 보여주고
하단에는 승인 완료한 인원을 보여주면 좋을 것 같습니다. 사실 승인이 완료된 경우에는 따로 신경 쓸 필요가 없기 때문에 상단에 대기 중인 인원만 체크하면 될 것 같습니다.

**Comment by 10001if** [comment]
1365 승인이 필요없는 경우에도 승인완료에서 보여주면 될 것 같습니다.

**Comment by 10001if** [comment]
![2015-09-09 2 10 52](https://cloud.githubusercontent.com/assets/4696328/9754050/e2cdff3a-56ff-11e5-9771-fe1bc4e21417.png)
텍스트를 입력하는 비고란이 있다면 필요한 내용들을 인수인계없이 전달 할 수 있을 것 같아요. 그리고.. 봉사자의 경우 이름만 알고 얼굴을 모르는 경우가 많은데, 사진을 업로드 하고 싶습니다. ^^

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/commit/f561d7ecd4d290617643971ddc871fbaaa78ad91
