### ISSUE TITLE
아름다운 가게의 자원봉사 시스템

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#14]
https://www.beautifulstore.org/Join/Volunteer/Process.aspx
참고할게 많을 것 같습니다. 공유차원에서 올립니다.

**Comment by aanoaa** [comment]
위 링크처럼 열린옷장에서의 봉사활동에 대한 소개 페이지가 있으면 좋을 것 같습니다.
어떤 방식으로 이루어지는지, 어떤 일을 하게 되는지 등등

안에 내용을 제가 채울 순 없는데, 어떻게 하는게 좋을까여?

**Comment by 10001if** [comment]
네~ 안그래도 저희가 만들어서 드려야 할 것 같아서. 자원봉사자 5분과 함께 실제로 어떤 일들을 하게 되는지, 무슨 내용인지 정리를 하고 있습니다. 간단하게라도 뼈대가 나오면 바로 말씀드릴게요.

**Comment by aanoaa** [comment]
페이지 디자인까지 나온다면 더 좋겠지만 그렇게 안된다면 들어갈 내용을 가지고 제가 레이아웃을 잡아봐야 합니다.

피드백받으면서 고쳐나가면 되겠죠

**Comment by 10001if** [comment]
@aanoaa 네! 아름다운가게만큼 좋은 프로그램을 가질 수 있을 것 같아 너무 신나네요. 감사합니다. :)

**Comment by pingpongworks** [comment]
참고 링크도 내용이 없어 닫겠습니다.
