### ISSUE TITLE
이름과 전화번호로 찾는 검색 창 추가 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#16]
이름 혹은 전화번호로 찾는 검색창이 있었으면 좋겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/commit/c6699ea9cb92cf7f4cf6f2f76420eba7b114185d

**Comment by aanoaa** [comment]
![screenshot-staff theopencloset net 5001 2015-09-14 16-16-26](https://cloud.githubusercontent.com/assets/170528/9844170/ff1cfbbe-5afb-11e5-8101-36c644a9861c.png)
