### ISSUE TITLE
봉사 예약시간 수정 시 캘린더에 반영이 안되는 오류 발견

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#17]
최민국님이 16일에 신청하셨다가 시간 변경 요청이 들어와 저희가 23일로 변경하여 수정했는데요.
그래도 캘린더에 반영이 되지 않네요. 확인 부탁드립니다~

**Comment by aanoaa** [comment]
아 승인 후에 변경이요?

**Comment by 10001if** [comment]
네~ 맞습니다. ^^
