### ISSUE TITLE
OT 소개 및 봉사활동 소개 페이지 제작

### ISSUE THREAD

**Issue by aanoaa** [opencloset/volunteer#20]
https://prezi.com/h9u3t2tkhw0d/ot/

**Comment by aanoaa** [comment]
http://opencloset.github.io/volunteer/

**Comment by aanoaa** [comment]
`docs` 디렉토리는 소개화면을 위한 공간입니다.
홈페이지 만들듯이 슥슥 해나가면 되지만 약간 다릅니다.

`README` 에 자세한 내용을 채워 나가도록 하겠습니다.

**Comment by 10001if** [comment]
![volunteer](https://cloud.githubusercontent.com/assets/4696328/12474082/5c477d36-c05b-11e5-8274-9d4e7835149c.jpg)
봉사신청 전에 본 페이지를 확인하고 버튼을 눌러 신청할 수 있도록 요청드립니다. 봉사 안내에 대한 정보가 전혀 없이 신청서만 작성하고 있는 경우가 많아 봉사 신청에 대한 기준 안내가 절실히 필요합니다. ^^

**Comment by 10001if** [comment]
@aanoaa 이 페이지 삽입은 시간 되시는 대로 바로 작업해 주시면 좋을 것 같습니다~ ^^

**Comment by aanoaa** [comment]
수정하고 배포하였습니다.

https://volunteer.theopencloset.net/
