### ISSUE TITLE
봉사자가 몇 번 방문했는지 확인할 수 있게 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#22]
![2015-09-14 12 37 49](https://cloud.githubusercontent.com/assets/4696328/9841684/df874516-5add-11e5-98f3-343fbc3e420c.png)
봉사자가 몇 번째 방문인지 알려면 자세히를 클릭해서 들어가야 하는데.
위 그림에서 바로 알 수 있도록 알려주면 좋겠습니다~
여러번 방문인 경우에는 자세히를 클릭해서 그 전에 어떤 활동을 했는지 필히 확인하도록 하겠습니다.

**Comment by aanoaa** [comment]
작업하면서 느끼는건데,
이런 이슈는 자원봉사에 관련된 건데 작업은 재고관리에서 이루어져야 합니다.

이슈 자체를 재고관리쪽으로 옮기는 것이 좋을까요 아님 이대로 두는 것이 좋을까요?

이슈를 옮기면 리포팅 하는 입장에서 좀 헛갈리는 것 같고요.
이대로 두면 이슈와 코드의 이력이 좀 분리됩니다.

cc @keedi, 의견을 부탁드립니다.
별 문제 없다고 생각하시면 지금처럼 자원봉사에 관한 이슈는 지금처럼 이 게시판을 그대로 사용하도록 하겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/commit/97f9e1f03c04816f103f12572e634a32abc91661

**Comment by aanoaa** [comment]
![screenshot-staff theopencloset net 5001 2015-09-14 18-02-55](https://cloud.githubusercontent.com/assets/170528/9846120/dc60a030-5b0a-11e5-9096-45a2453726d9.png)

`51번째 방문` 이라고 보입니다.

**Comment by aanoaa** [comment]
자원봉사자 목록을 volunteer 서비스에서 가져오고 재고관리에서는 보여주기만 하도록 하면 될 것 같습니다.

**Comment by aanoaa** [comment]
자바스크립트쪽이 좀 더렵혀지겠지만 관리 부분에선 더 용이할 것 같습니다.
