### ISSUE TITLE
1365에는 신청했지만 열린옷장에는 신청하지 않은 사용자 찾기

### ISSUE THREAD

**Issue by aanoaa** [opencloset/volunteer#23]
1365시간이 필요한 사용자는 두군데에서 신청을 해야 합니다.
- 1365
- 열린옷장 자원봉사

헌데 1365에서는 신청하였지만 열린옷장에 신청하지 않은 사용자를 찾아낼 방법은
눈으로 비교하는 것 밖에 없습니다.

이를 편리하게 찾을 수 있는 방안을 마련해야합니다.

**Comment by 10001if** [comment]
엑셀파일로 다운로드 받을 수 있습니다.
이파일을 그대로 업로드하게 된다면 좋을 것 같습니다.

형식은 아래와 같습니다.

|  |
| --- |
| 순번,봉사자성명,생년월일,연락처,휴대폰,소속센터 |
| 1,,,,,경기도 용인시 |
| 2,,,,,서울특별시 광진구 |
| 3,,,,,경기도 안양시 |
| 4,,,,,서울특별시 강동구 |
| 5,,,,,서울특별시 광진구 |
| 6,,,,,서울특별시 광진구 |
| 7,,,,,서울특별시 송파구 |
| 8,,,,,서울특별시 동대문구 |
| 9,,,,,서울특별시 중랑구 |
| 10,,,,,서울특별시 중랑구 |
| 11,,,,,서울특별시 중랑구 |
| 12,,,,,서울특별시 광진구 |
| 13,,,,,서울특별시 광진구 |
| 14,,,,,서울특별시 광진구 |
| 15,,,,,서울특별시 광진구 |
| 16,,,,,서울특별시 광진구 |
| 17,,,,,서울특별시 광진구 |
| 18,,,,,서울특별시 광진구 |
| 19,,,,,서울특별시 광진구 |
| 20,,,,,서울특별시 광진구 |
| 21,,,,,서울특별시 광진구 |
| 22,,,,,서울특별시 강동구 |
| 23,,,,,서울특별시 중랑구 |
| 24,,,,,서울특별시 마포구 |

**Comment by aanoaa** [comment]
| 순번 | 봉사자성명 | 생년월일 | 연락처 | 휴대폰 | 소속센터 |
| --- | --- | --- | --- | --- | --- |
| 1 |  |  |  |  | 경기도 용인시 |

**Comment by aanoaa** [comment]
날짜가 생년월일이네요.
활동일이 필요할 것 같은데..

**Comment by aanoaa** [comment]
이름만으로 csv or xls 파일에는 있고, DB 에는 없는 사용자를 찾아야 하는데,
오늘날짜를 기준으로 앞뒤 7일 해서 이름이 없으면 아직 신청 안한 사용자로 보여주는게 괜찮을 것 같습니다.

**Comment by aanoaa** [comment]
일단 전에 신청한 이력이 있는 사람이면 날짜와 시간만 선택해서 간편하게 staff가 대신 신청할 수 있도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa  전에 열심히 작업 해주셨는데.. 뾰족한 수가 없으니 우선 닫아도 될 것 같습니다.
