### ISSUE TITLE
자원봉사 신청서 상에 "열린옷장에서 어떤 활동에 관심있나요?" 삭제

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#25]
자원봉사 신청서에 "반납 및 정리" "포장 및 정리"를 묻는 항목을 삭제하였으면 좋겠습니다. 이 부분은 향후에 할 일이 완벽히 정리된 이후에 PDF 나 동영상 혹은 OT를 통해 할 일에 대한 숙지가 이루어진 뒤에나 의미가 있을 것 같습니다. 현재는 두개 중 무엇을 선택해도 어떤 일을 하는지 그게 무엇인지 알기가 힘들 것이므로 우선 당분간은 이 항목은 받지 읺았으면 좋겠습니다. :)

**Comment by 10001if** [comment]
현재 승인 후 문자발송 될때 어떤 업무를 하게 될 것이라고 고지가 나가는데, 이것도 발공되지 않도록 해야할 것 같습니다.

**Comment by aanoaa** [comment]
이미 고쳤습니다.
