### ISSUE TITLE
봉사자의 정보 '자세히' 보는 경우에 내부 정보 수정  

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#28]
현재 생년월일이 표시되지 않고 있습니다. 생년 월일 표시 요청드립니다.
그리고 윈도우 화면에서 자세히를 누르고 들어 갔을 때 전화번호 끝부분이 가려져 보이지 않는 현상이 있습니다.

**Comment by 10001if** [comment]
@aanoaa 생년월일 표시는 빨리 되었으면 좋겠습니다~ ^^

**Comment by aanoaa** [comment]
> 그리고 윈도우 화면에서 자세히를 누르고 들어 갔을 때 전화번호 끝부분이 가려져 보이지 않는 현상이 있습니다.

IE 말씀하시는건가요?

**Comment by 10001if** [comment]
네~ 맞습니다~!

**Comment by pingpongworks** [comment]
현재 프로그램에 필요하지 않은 이슈라 닫겠습니다.
