### ISSUE TITLE
봉사활동 방문창에서 봉사일 기준으로 정렬이 되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#35]
승인대기중인 상태 내에서도 봉사일이 이른 순서대로 정렬이 되어야 하는데 되지 않고 있습니다. 수정 부탁드립니다.

**Comment by aanoaa** [comment]
오늘 데이터 기준으로는 확인하기 어려워서 스크린캡쳐가 있으면 더 이해하기 좋을 것 같습니다.
잘못되어있는 화면을 캡쳐해주시고 어떻게 바뀌어야 한다고 알려주세요.
