### ISSUE TITLE
오늘 방문한 자원봉사자에게 SMS 전송이 안됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/volunteer#36]
등록해놨는데 안됨.

**Comment by aanoaa** [comment]
```
0,KR::APIStore,50824,07043257521,010-xxxx-xxx,수고하셨습니다. 오늘 봉사활동 어떠셨나요? 다음 주소에 접속해 방명록을 남겨주세요. 남겨주신 방명록은 다음 봉사자 분들을 위해 활용됩니다. https://volunteer.theopencloset.net/works/88/guestbook?authcode=XxXxxxxxXXxXxxxxXxXXxXxxXXXXxXXx
```

이런 로그를 발견했습니다.
받는번호 형식이 `010-xxxx-xxx` 여서 받지 못한 것 같습니다.

다른 정상적인 로그를 보면, `010xxxxxxxx` 입니다.

**Comment by keedi** [comment]
`OpenCloset::Cron::SMS` 모듈 릴리스 후 서버에 설치 및 해당 크론 스크립트 재기동했습니다.

**Comment by aanoaa** [comment]
오늘 19:00 이후에 로그를 확인해보겠습니다.

**Comment by aanoaa** [comment]
어제는 자원봉사자가 없었기 때문에 로그가 기록되지 않았습니다. 오늘은 있으니까 더 지켜보도록 하겠습니다.

**Comment by aanoaa** [comment]
정상적으로 발송된 로그를 확인했습니다.
