### ISSUE TITLE
방명록이 등록되면 알람

### ISSUE THREAD

**Issue by aanoaa** [opencloset/volunteer#37]
방명록이 등록되면, 일단은 `volunteer@theopencloset.net` 으로 노티 메일을 받고 싶습니다.

**Comment by 10001if** [comment]
이메일 전송이 이루어지지 않는 것 같습니다. 확인 부탁드리겠습니다. ^^

**Comment by 10001if** [comment]
이메일 전송이 정상적으로 이뤄지고 있습니다. 이슈 닫도록 하겠습니다.
