### ISSUE TITLE
활동내용

### ISSUE THREAD

**Issue by aanoaa** [opencloset/volunteer#4]
- 열린옷장 활동이 한개만 선택가능하도록 변경해야 합니다.
- 승인 후에 달력에 어떤 활동을 하는지 표시되어야 합니다.

**Comment by aanoaa** [comment]
완료하였습니다.

**Comment by 10001if** [comment]
승인 후에 달력에 어떤 활동을 하는지 표시되어야 합니다. -> 아직 적용이 되지 않은 것 같습니다.
확인 부탁드립니다. ^^
![2015-08-22 12 09 23](https://cloud.githubusercontent.com/assets/4696328/9422231/bc625270-48c6-11e5-987b-d26a895a59dd.png)

**Comment by aanoaa** [comment]
저거 저번에 테스트해본거 안지운거고 지금은 될 거 같습니다. 안해봤지만..
