### ISSUE TITLE
봉사신청할때 업무담당 등 질문선택 답을 의무화

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#40]
봉사 신청시 작성하는 질문란의 선택을 의무화 할 수 있도록 변경 요청드립니다.

**Comment by aanoaa** [comment]
의무화해야 하는 질문에 대해 선택해주세요.
- [x] 1365 승인이 필요하십니까?
- [x] 1365 홈페이지에서 신청서를 작성하셨습니까?
- [x] 열린옷장을 만나게 된 이유를 선택해주세요
- [x] 열린옷장 지원활동에 처음 접한 경로를 선택해주세요
- [ ] 열린옷장에서 얼마동안 활동하실 예정이신가요?
- [x] 해당 직업에 선택해주세요
- [x] 그 이외에 열린옷장과 연관된 재능이 있다면 적어주세요
- [ ] 열린옷장에서 활동에 대해 자유롭게 적어주세요

**Comment by 10001if** [comment]
네~ 확인해서 의견 남겨놓겠습니다 ^^

**Comment by 10001if** [comment]
1365 승인이 필요하십니까?
 1365 홈페이지에서 신청서를 작성하셨습니까?
 열린옷장을 만나게 된 이유를 선택해주세요
 열린옷장 지원활동에 처음 접한 경로를 선택해주세요
해당 직업에 선택해주세요
그 이외에 열린옷장과 연관된 재능이 있다면 적어주세요

이것만 의무화하면 됩니다. ^^

**Comment by 10001if** [comment]
@aanoaa 요것도 마무리 된 것 같습니다. ^^
