### ISSUE TITLE
자원봉사 시간표에서 시작시간과 종료시간이 함께 표시되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#42]
현재는 시간표에 시작시간만 표기되고 있습니다. 때문에 언제 방문하는지는 알 수 있지만 10시에 와서 언제까지 봉사를 하는지는 시간표에서는 확인하기 어려운데요. 시작시간 외에 종료시간도 함께 표기되었으면 좋겠습니다.

**Comment by aanoaa** [comment]
구글 캘린더 말씀하시는거라면,
클릭하면 from ~ to 가 나타납니다.
캘린더에 종료시간을 표시할 수 있는 방법을 우선 찾아봐야합니다.

**Comment by aanoaa** [comment]
여기 오래된 구글제품에대한 포럼 스레드가 있네요.
https://productforums.google.com/forum/#!topic/calendar/ZryGKmyOTJA

제가 설정에가서 찾아봐도 없었고요.
월별로 시작 시간과 끝나는 시간을 함께 나타낼 수 없습니다.

**Comment by aanoaa** [comment]
week 혹은 agenda 로 보면 종료시간을 함께 볼 수 있습니다.
