### ISSUE TITLE
봉사승인시 밴드 가입문자가 발송되지 않도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#43]
봉사승인을 해보았는데요. 승인 후 전송되는 문자가 발송되지 않고 있습니다. 위치, 승인내역, 밴드 가입 문자가 발송되어야 하는데. 밴드 가입 문자만 발송되고 있습니다. 확인 부탁드릴게요 ^^

**Comment by 10001if** [comment]
제가 직접 다시 확인해보니 문자가 정상적으로 발송됩니다. 5층의 옷장지기 핸드폰으로 확인했을 때는 밴드 가입문자만 발송되고 있었는데, 문자가 발송되지 않는 부분들을 이걸로 확인해볼 수 있지 않을까 싶습니다. ^^ 아이폰을 사용하고 있고 LGU+를 사용하고 있습니다~

**Comment by 10001if** [comment]
현재는 밴드를 사용하지 않는다고 합니다. 봉사승인시 밴드가입문자는 발송되지 않도록 수정 요청드립니다.

**Comment by aanoaa** [comment]
밴드를 사용하지 않게 된 건 좋은징조인가요?

**Comment by aanoaa** [comment]
봉사활동 신청이 승인되고 나면 아래 문자 메세지가 발송되고 있습니다.

```
열린옷장의 소식이나 열린옷장 봉사자분들과 친목을 위한 네이버 밴드가 있습니다.
관심있음 가입하셔서 누구나 열린옷장을 즐길 수 있습니다. 
http://www.band.us/#!/band/53901580
```

이 문자메세지를 안보내는게 맞겟죠?

**Comment by aanoaa** [comment]
열린옷장 봉사활동 밴드 커뮤니티가 없어진 건가요?
