### ISSUE TITLE
같은시간에 봉사활동 신청이 2번 연속으로 되지 않도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#47]
의견을 들어보니 같은시간에 여러번 신청이 되는 경우가 있어 혼란이 있다고 합니다.
신청이 중복되지 않도록 수정을 요청드립니다. ^^

**Comment by aanoaa** [comment]
동일한 정보를 가지고 같은 날 한번 이상 신청하지 못하도록 하면 될까요?
신청된지 모르고 또 신청하는 경우인가요?
왜 두번 신청하는거죠?
같은 날 신청하면 이미 신청되었습니다. 정도로 보여주면 될까요?

**Comment by aanoaa** [comment]
> 같은날 두번 이상 신청할 수 없습니다
