### ISSUE TITLE
봉사활동이 승인된 봉사자에게 SMS 보내는 문구 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#48]
봉사활동이 승인되면
여러 문자가 발송되고 있습니다.
1365등 안내문자와 밴드 가입문자 그리고 위치 안내 문자가 발송되고 있습니다.

그 중에서 위치 안내 문자에 웅진빌딩 203호로 방문해 달라고 문구를 수정 요청드립니다.

현재는 203호에서 봉사활동에 대한 안내를 드리고 봉사활동을 진행하고 있습니다.

**Comment by aanoaa** [comment]
더불어 밴드 가입안내 내용도 빠져야 합니다.

**Comment by aanoaa** [comment]
**203**

**Comment by aanoaa** [comment]
> 더불어 밴드 가입안내 내용도 빠져야 합니다.

81fb883c0e66b4a59740a6cd3271edc0aae5f582

**Comment by aanoaa** [comment]
https://github.com/opencloset/volunteer/commit/6e5175e8d95f39319d7163dcc8656e0dc03ed0ae

**Comment by 10001if** [comment]
@aanoaa 발송되는 문자 내용 중 `203호`로 방문한다는 문자 내용 대신 `B03호`로 방문해 달라고 수정 부탁드립니다. 금일 부로 203호는 사용하지 않기 때문입니다.

**Comment by 10001if** [comment]
@aanoaa ASAP로 요청드립니다. ^^

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1026

**Comment by keedi** [comment]
> @aanoaa 발송되는 문자 내용 중 203호로 방문한다는 문자 내용 대신 B03호로 방문해 달라고 수정 부탁드립니다. 금일 부로 203호는 사용하지 않기 때문입니다.

#72 이슈로 열어 처리하겠습니다. 이슈 닫습니다.
