### ISSUE TITLE
신청서와 방명록내용 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/volunteer#5]
- 성별과 직업이 신청서에
  - 성별은 위에, 직업은 아래에

> 열린옷장에서 어떤 활동에 관심있나요?
- 반납 및 정리
- 의류포장 및 정리

**help** 각 4,5층 활동으로 나뉘어져 있으며 4층은 반납 및 정리, 5층은 의류포장
및 정리 입니다

**Comment by 10001if** [comment]
오늘 활동은? 
1. 반납 및 정리 
2. 의류 포장 및 정리 
3. 전화안내 및 제반업무 ( 향수 만들기 등 ) 
4. 현장 안내

다음에 하고 싶은 활동? 
1. 반납 및 정리 
2. 의류 및 포장 
3. 전화안내 및 제반업무
4. 현장 안내 

오늘 활동은 어떠셨나요?
1. 힘들었음
- 힘들었다면 그 이유는 ? 바쁜활동 / 인간관계 / 지루한 활동 / 다른 활동 관심 / 기타
1. 그저 그럼
2. 재미있었음

**Comment by aanoaa** [comment]
방명록에서 `연령대` 도 삭제해야합니다.
