### ISSUE TITLE
자원봉사자가 봉사신청을 2회 이상 신청할 수 있도록 복수 신청을 허용하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#51]
자원봉사자가 봉사신청을 하는 경우 재신청 하는 경우 이름과 전화번호가 일치하는 경우 기존 정보를 불러오도록 하였으면 합니다. 5번 이상 신청하는 자원봉사자의 경우 입력하는 것에 불편함을 느낀다는 의견이 많았습니다. 확인부탁드립니다.

**Comment by aanoaa** [comment]
비밀번호가 있는게 아닌데, 불러와지게 된다는 것은 누군가가 이름과 전화번호를 알면 주소, 이메일등을 알아낼 수 있다는 말입니다.

**Comment by 10001if** [comment]
@aanoaa 생각해보니 그러네요.. 조금 더 고민을 해보고 다시 말씀드리겠습니다.

**Comment by 10001if** [comment]
@aanoaa 그렇다면 비밀번호를 부여하는 것은 어떨까요? 개인적으로 선호하지는 않는데, 여러번 신청하시는 분들의 경우에 주소들을 매번 작성하는게 불편하다고 하시네요. 아직 저도 뚜렷한 아이디어가 없습니다. 당장 급한 사항은 아니니 조금 더 생각해 보고 말씀드리도록 하겠습니다.

**Comment by aanoaa** [comment]
봉사활동 신청하는데 비밀번호를 입력한다는게 좀 이상하긴 합니다.
신청할때에 복수일로 신청할 수 있다면 좋을 것 같네요.

**Comment by 10001if** [comment]
@aanoaa 그 방법도 좋네요! 비밀번호는 저도 좀 이상한 것 같습니다...

**Comment by 10001if** [comment]
@aanoaa 신청할 때 복수일로 선택하게 하는 것이 좋은 생각인 것 같습니다. 이 부분 때문에 불편함을 호소하는 연락이 많이 들어오고 있습니다. 실제로 열린옷장 봉사가 2회 이상인데. 신청 시에는 한번 밖에 신청할 수 없어 불편함이 많이 발생하고 있습니다.

**Comment by 10001if** [comment]
복수로 신청하도록 하는 기능이 필요합니다. 최근들어 정기적으로 봉사하려는 분들이 늘어 나고 있습니다. 하지만 그때마다 여러번 신청해야 하는 번거로움이 발생하여 이런 문제를 해결하고자 합니다.

**Comment by aanoaa** [comment]
수락과도 관계가 있습니다.
수락될때마다 sms 가 전송될텐데 한번에 수락할지 나눠서 할지는 모르겠습니다.

일단 복수일로 신청할 수 있도록 하겠습니다.
수락과정에서 불편이 있으면 다시 알려주세요.

**Comment by aanoaa** [comment]
선택일별로 활동시간을 선택할 수 있어야 하고, 각각 수락할 수 있어야 합니다.

**Comment by aanoaa** [comment]
여러개 선택된 날짜와 시간을 확인할 수 있도록 해줘야 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 승인이랑 관계가 있겠네요. 얼마 전에 봉사자에 관한 회의를 할 때 승인의 필요성에 대한 이야기가 나왔습니다. 신청-승인에서 제한요소가 없는 상황이라 신청=승인인 상황인 것 같아 승인이 정말 필요한지 문의가 있었습니다. 우선 사용해보고 불편이 있으면 다시 말씀드리도록 하겠습니다.

**Comment by aanoaa** [comment]
같은 사람이 같은날에 신청할 수 있습니다.

- 14일 10 ~ 13시
- 14일 14 ~ 18시
- 14일 10 ~ 18시

3건 모두 승인하게 되면 한명의 중복된 신청에 의해 다른 봉사자가 신청을 할 수 없게 될 수 있습니다.

**Comment by aanoaa** [comment]
봉사활동 신청후에 아래의 문자메세지를 받게 됩니다.

> 안녕하세요. xxx님이 xx월 xx일 xx~xx시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.
> 현재 열린옷장 담당자가 접수된 봉사신청 내역을 확인하고 있습니다. (최종승인까지 소요기간 1일 이내)
> 신청하신 봉사시간 및 봉사활동내역에 대해 변경사항이 없는 경우 xxx님이 신청해 주신 자원봉사에 대한 최종승인여부가 SMS로 발송될 예정입니다.
> 봉사 승인에 대한 SMS 또는 전화연락이 없는 경우 02-6929-1020 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

여러개를 한번에 신청할때에는 내용이 바뀌어야 할 것 같습니다.

    안녕하세요. xx월 xx일 xx~xx시, xx월 xx일 xx~xx시, xx월 xx일 xx~xx시, xx월 xx일 xx~xx시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.

처럼 바뀌거나 일만 표시하거나..

    안녕하세요. xx월 xx일, xx월 xx일, xx월 xx일에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.

**Comment by 10001if** [comment]
@aanoaa 좀 지저분 할 수 있지만.. 안녕하세요. xx월 xx일 xx~xx시, xx월 xx일 xx~xx시, xx월 xx일 xx~xx시, xx월 xx일 xx~xx시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.로 해야 시간까지 정확히 확인할 수 있을 듯 합니다.

**Comment by 10001if** [comment]
@aanoaa 현재 열린옷장 봉사는 2회 신청을 기본으로 하고 있습니다. 강제로 2회 봉사를 입력할 수 있도록 수정 요청드립니다. 봉사 신청일 입력란을 2개는 기본으로 열어두고 그 이상의 경우 추가하여 신청할 수 있도록 수정 요청드립니다.

**Comment by 10001if** [comment]
> 같은 사람이 같은날에 신청할 수 있습니다.
> 
> 14일 10 ~ 13시
> 14일 14 ~ 18시
> 14일 10 ~ 18시
> 3건 모두 승인하게 되면 한명의 중복된 신청에 의해 다른 봉사자가 신청을 할 수 없게 될 수 있습니다.

그러네요. 승인의 의미가 분명히 존재하네요. 알겠습니다.

**Comment by 10001if** [comment]
![2017-04-14 10 10 21](https://cloud.githubusercontent.com/assets/4696328/25029687/9fefdda2-20fa-11e7-9601-fa2bc9075070.png)
1회 신청 후에도 복수로 신청할 수 있다는 내용이 적혀 있지 않아, 여러 날을 복수로 신청할 수 있다는 사실을 인지하지 못할 것 같습니다.  따라서 현재 멘트인 `예약가능한 활동시간만 선택가능합니다. 예약이 완료된 시간은 선택이 불가능합니다.`대신 

`봉사 신청은 복수로 가능합니다. 1회 신청 후, 추가로 신청일과 시간을 입력해주세요. 다만, 예약이 완료된 시간은 선택이 불가능합니다. 예약가능한 활동시간만 선택해주세요.`로 수정 요청드립니다.
