### ISSUE TITLE
오늘까지 접수된 자원봉사자의 목록을 파일로 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#52]
자원봉사자에게 뉴스레터를 발송해야 하는 이슈가 있습니다. 자원봉사자 사이트에서 접수된 자원봉사자의 이름 / 전화번호 / 이메일 파일을 전달 받고 싶습니다. 금일 중으로 요청드려도 될까요? ^^

**Comment by aanoaa** [comment]
메일을 전달 했습니다.
