### ISSUE TITLE
화목 에 왜 신청안되는지에 대한 안내문구 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/volunteer#54]
```
매주 화목은 정기적인 기업봉사일입니다.
```

**Comment by aanoaa** [comment]
1e002bf10cf45f54f3bc4ed8dd436327a63bca12

**Comment by aanoaa** [comment]
> 매주 화목은 정기적인 기업봉사일입니다. 

이거는 기간이 끝난거죠?

**Comment by 10001if** [comment]
@aanoaa 15일 부터는 이 문구가 없어져야 합니다. 14일까지는 필요합니다. ^^
