### ISSUE TITLE
봉사 신청자에게 방문 당일 문자를 발송하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#55]
[열린옷장] 000님 안녕하세요 좋은 아침입니다:) 오늘은 열린옷장과 함께 봉사활동 하는 날인 것 잊지 않으셨죠? 이따 밝은 모습으로 뵙겠습니다!

자원봉사를 신청한 인원 중 승인이 된 인원에게 봉사 신청 당일이 되면 오전 8시에 발송이 되도록 요청드립니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/766

**Comment by aanoaa** [comment]
`OpenCloset-Cron-SMS-0.007.tar.gz` 파일을 설치하고 재시작해야 합니다.

**Comment by aanoaa** [comment]
파일을 업그레이드 하고 `opencloset.cron.sms` 서비스 재시작 하였습니다.
내일 방문하는 자원봉사자에게서 문자메세지를 확인해주세요.

**Comment by 10001if** [comment]
오늘 확인해 보니까 문자를 못 받았다고 합니다. ㅠ

**Comment by aanoaa** [comment]
로그상에서 실제로 sms 가 전송되지 않았습니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/799
