### ISSUE TITLE
봉사신청 시 `1365 로그인 아이디를 적는 란`의 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#59]
봉사시간을 인증해 주기 위해서는 1365에 접속하여 봉사자의 신청내역을 확인. 봉사 승인을 실시해야 합니다. 

그러나 1회 신청 내역이 있는 경우 봉사자의 로그인 아이디만 알고 있으면 신청없이도 관리자(열린옷장)가 봉사 신청 승인 요청을 할 수 있습니다. 현재는 이름과 거주지로 확인하고 있는데, 로그인 아이디만 알면 간단히 해결이 됩니다. 

따라서 신청 시 1365 봉사 실적이 필요한 봉사자에게는 1365 로그인 아이디를 받을 수 있도록 하였으면 합니다. 세부 내용은 다음과 같습니다.

![2016-06-09 5 27 27](https://cloud.githubusercontent.com/assets/4696328/15923453/3e9b9c9c-2e68-11e6-82f0-a30e44d3276d.png)

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/856

**Comment by aanoaa** [comment]
OpenCloset::Schema 0.036 이상 버전을 필요로 합니다.
