### ISSUE TITLE
9월 24일(일)부터 일요일 영업을 시작함에 따라 봉사신청 인원을 2인으로 변경하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#61]
기존에는 일요일에는 영업을 하지 않았기 때문에 봉사자 신청을 받지 않았습니다. 하지만 24일부터 일요일 영업을 실시할 예정이므로 일요일도 평일과 같이 2명의 봉사자를 받을 수 있도록 수정요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/931

**Comment by aanoaa** [comment]
모든일요일을 빼거나 말거나 하는 이슈입니다.
9월 18일 이후에 작업반영해야합니다.

방법이 있긴 하지만, 18일 이후에 작업해서 반영하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 봉사자 수를 3인으로 변경 요청드립니다. 이번 주부터 일요일이 오픈되는 관계로 금일 중으로 작업을 요청드립니다~ ^^

**Comment by 10001if** [comment]
정상적으로 봉사 신청이 되지 않습니다. 다시 한번 확인 부탁드립니다.
