### ISSUE TITLE
추석연휴 기간인 2016년 9월 14일부터 9월 18일까지 봉사 신청을 받지 않도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#62]
추석연휴 기간인 2016년 9월 14일부터 9월 18일까지 봉사 신청을 받을 수 없도록 신청조정을 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/940

**Comment by aanoaa** [comment]
00efed08a955b1eb000ef281735ca8830ddd901c
