### ISSUE TITLE
자원봉사자 신청서에 답변된 내용의 통계

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#64]
신청서에 답변된 모든 내용들의 횟수와 비율에 대한 정보를 전달받고자 합니다.

예)
1. 열린옷장을 만나게 된 이유를 선택해주세요

| 목적 | 횟수 | 비율 |
| --- | --- | --- |
| 봉사시간 | 100 | 23% |
| 봉사활동에 관심 있어서 | 120 | 25% |
| 열린옷장에 관심 있어서 | 40 | 5% |
| 사회경험 | 50 | 7% |
| 개인시간 활용 | 150 | 32% |
| 1365 사이트 | 74 | 12% |
| 기타 | 10 | 3% |
| 합계 | 360 | 100% |

숫자는 이해를 돕기 위해 임의로 넣었습니다.

**Comment by yongbin** [comment]
`volunteer_work` 테이블의 내용을 요약해야합니다.

**Comment by 10001if** [comment]
@yongbin #63 이슈와 마찬가지로 다음 주 월요일(24일)까지 정보가 꼭 필요합니다. 화요일에 자원봉사와 관련된 전체 회의가 진행될 예정입니다.

**Comment by yongbin** [comment]
https://volunteer.theopencloset.net/works/new 에 존재하는 질문중 아래 6가지에 대한 요약 정보를 작성하면 됩니다. 
1. 1365 승인이 필요하십니까?
2. 1365 홈페이지에서 신청서를 작성하셨습니까? 
3. 열린옷장을 만나게 된 이유를 선택해주세요(Multi)
4. 열린옷장 지원활동에 처음 접한 경로를 선택해주세요 (Multi)
5. 열린옷장에서 얼마동안 활동하실 예정이신가요?
6. 해당 직업에 선택해주세요

Multi 인 컬럼들은 풀어서 처리되어야 합니다.

**Comment by yongbin** [comment]
쿼리로 얻은 내용을 피봇테이블로 정리했습니다.

![screenshot 2016-10-25 04 07 12](https://cloud.githubusercontent.com/assets/52704/19659877/a3260fb4-9a68-11e6-913a-fe6f54f59520.png)
![screenshot 2016-10-25 04 07 27](https://cloud.githubusercontent.com/assets/52704/19659878/a4d15bf2-9a68-11e6-8dc1-4c22519983d1.png)
![screenshot 2016-10-25 04 07 39](https://cloud.githubusercontent.com/assets/52704/19659881/a6cce156-9a68-11e6-959f-81d46e08d758.png)

**Comment by yongbin** [comment]
해당파일을 메일로 전달합니다.

**Comment by yongbin** [comment]
메일 발송했습니다.
