### ISSUE TITLE
자원봉사자 신청서 기입내용 중 생년월일 입력란에 연령제한 표시를 추가 

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#66]
자원봉사 신청서 기입 내용 중 생년월일 입력란에 현재는 `생년월일 ex)1988-12-04`로 작성되어 있습니다.

하지만 내부적인 지침이 변경되어 앞으로는 고등학생 이상 봉사자들에게만 신청을 받으려고 합니다. 
따라서 생년월일 입력란에 `생년월일 ex)1988-12-04, 17세(고등학생)이상만 봉사 신청이 가능합니다.`로 수정 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/995

**Comment by aanoaa** [comment]
17세 이상만 봉사신청이 가능하게 하려면 안내문구만으로는 부족하고,
생년월일 입력에 따라 더이상 진행이 불가하도록 만드는 것이 더 좋습니다.

**Comment by aanoaa** [comment]
d73cb84f621f1cd9ed184d2be3885a1d69b32c71
