### ISSUE TITLE
1365 신청에 관한 문자, 이메일, 안내 내용을 삭제하고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#68]
1365 신청서 작성이 필요없어짐에 따라 이에 관한 문자, 이메일, 안내 내용을 삭제하고자 합니다.
방금 확인한 바로는 
- [x] 1365 신청 안내문자
- [x] 신청서 작성 후 나타나는 1365 신청서 작성 안내
  에 1365 신청 내용이 들어가 있었습니다. 이상 두 내용은 문자 미발송 & 식청서 작성 안내 내용 삭제 요청드립니다.

하지만, 신청 후 발송되는 이메일에 어떤 내용이 들어 있는지 확인하지 못했습니다.
이메일에 1365 신청에 관한 내용이 있는지 확인 부탁드리겠습니다. ^^

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/999

**Comment by aanoaa** [comment]
> [열린옷장 봉사활동 신청접수] xxx님이 봉사활동을 신청하셨습니다.

이메일은 위내용을 제목으로 보내고 본문은 없습니다.
