### ISSUE TITLE
봉사자 스스로 봉사 신청을 취소하거나 시간을 변경할 수 있는 기능추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#69]
봉사자 스스로 봉사 신청을 취소하거나 시간을 변경할 수 있는 기능추가를 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1000

**Comment by 10001if** [comment]
@aanoaa 1000번째 이슈입니다. 👍

**Comment by aanoaa** [comment]
활용되지 않고 있지만 스스로 봉사활동에 관련된 내용을 수정할 수 있는 기능은 있습니다.
신청자에게 이메일로 수정할 수 있는 링크를 전송하려고 했는데 이메일 대신에 SMS 를 보내도록 한 것 같습니다.

취소할 수 있도록 기능을 추가 하도록 하겠습니다.

특별한 아이디어가 없다면, 취소가능한 url 을 봉사활동 신청 후 전송되는 SMS 에 포함시켜서 안내하도록 하겠습니다.

**Comment by aanoaa** [comment]
신청서의 상태를 확인해봐야 합니다.

승인전 / 승인후

승인전 취소는 상관없습니다.
승인후에는 캘린더에서도 지워져야 할테고 담당자가 알아야 할 필요가 있을 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 승인 후 취소에 대해서만 메일로 알림 발송받도록 하면 될 것 같습니다.

**Comment by aanoaa** [comment]
승인된 신청서를 취소하였을때에,

- 대표 이메일로 취소에 관련된 이메일을 보내야 합니다.
- 캘린더에서 해당 내용을 삭제하여야 합니다.

**Comment by aanoaa** [comment]
신청후에 발송되는 SMS 입니다.

> 안녕하세요. xxx님이 xx월 xx일 xx~xx시에 신청하신 자원봉사신청이 정상적으로 접수되었습니다.
> 현재 열린옷장 담당자가 접수된 봉사신청 내역을 확인하고 있습니다. (최종승인까지 소요기간 1일 이내)
> 신청하신 봉사시간 및 봉사활동내역에 대해 변경사항이 없는 경우 xxx님이 신청해 주신 자원봉사에 대한 최종승인여부가 SMS로 발송될 예정입니다.
> 봉사 승인에 대한 SMS 또는 전화연락이 없는 경우 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.

여기에 취소에 관련된 내용을 넣어야 합니다.
취소할 수 있는 url 은 `https://volunteer.theopencloset.net/works/:id/cancel?phone=xxxx` 입니다.

@10001if 위 내용을 넣어서 적절하게 만들어 주세요.

**Comment by aanoaa** [comment]
승인된 봉사활동을 취소했을때에는 아래내용으로 알람 이메일을 보냅니다.

> From: volunteer@theopencloset.net
> To: info@theopencloset.net
> Subject: [열린옷장 승인된 봉사활동 취소] xxx님이 봉사활동을 취소하였습니다.
> Date: Thu, 24 Nov 2016 16:01:05 +0900
> 
> --

**Comment by aanoaa** [comment]
@10001if 왈: 신청후 안내 메세지가 아닌 승인 후 안내메세지에 취소 관련 내용이 포함되어야 합니다.

**Comment by aanoaa** [comment]
> 축하합니다! xxx님이 xx월 xx일 xx~xx시에 신청하신 봉사활동이 최종 승인 완료되었습니다.
> 추가로 궁금한 점이 있는 경우에는 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 봉사당일 밝은 얼굴로 인사드리겠습니다. 감사합니다.

이게 승인 후 메세지 입니다.

**Comment by aanoaa** [comment]
> 신청하신 봉사활동이 최종 승인 완료되었습니다.

대신에

    신청한 봉사활동이 승인되었습니다.

가 더 적절한 것 같습니다.
그리고 축하할 것 까지야..

**Comment by 10001if** [comment]
```
xxx님이 xx월 xx일 xx~xx시에 신청하신 봉사활동이 승인되었습니다.

신청한 봉사일에 방문할 수 없는 경우, 신청한 봉사활동을 취소하려면 다음의 URL을 눌러 취소해주세요. 봉사취소는 봉사 신청일 하루 전까지만 가능합니다. 봉사 신청 후 미방문하는 경우, 결원으로 인한 운영상의 어려움이 발생합니다. 미방문시에는 꼭! 봉사신청을 취소해주세요.
 
봉사신청과 관련하여 추가적으로 문의사항이 있는 경우 070-4325-7521 혹은 카카오톡 옐로아이디를 통해 문의해주시기 바랍니다. 감사합니다.
```
