### ISSUE TITLE
자원봉사자에게 보내는 문자 메시지에 변경된 사무실 위치를 반영

### ISSUE THREAD

**Issue by keedi** [opencloset/volunteer#72]
@10001if wrote:
> 발송되는 문자 내용 중 203호로 방문한다는 문자 내용 대신 B03호로 방문해 달라고 수정 부탁드립니다. 금일 부로 203호는 사용하지 않기 때문입니다.

**Comment by aanoaa** [comment]
서버에 반영하였습니다.

**Comment by pingpongworks** [comment]
@aanoaa 봉사자에게 발송되는 문자내용 중 B03호로 방문한다는 문자 내용 대신 **5층 열린옷장**으로 방문해 달라고 수정 부탁드립니다. 앞으로 봉사자 안내를 5층에서 담당할 예정이기 때문입니다.

**Comment by pingpongworks** [comment]
@aanoaa 지하 사무실에 아무도 없는 날이 많아지고 있어, 이미 5층에서 봉사자 안내를 담당하고 있습니다. 모든 봉사자가 지하로 왔다가 5층으로 가고 있어서 가능한대로 문자 수정 부탁드립니다. 

![image](https://user-images.githubusercontent.com/17288038/34929802-4b5571a6-fa09-11e7-9e35-4a364e61f6b2.png)

빨간 밑줄 부분 대신 **5층 열린옷장으로** 수정해주시면 됩니다.

**Comment by 10001if** [comment]
@pingpongworks 그럼 `해당건물 5층 열린옷장으로 오시면 됩니다`로 수정하면 될까요?

**Comment by pingpongworks** [comment]
네 그렇습니다.

**Comment by aanoaa** [comment]
수정하고 반영하였습니다.

**Comment by 10001if** [comment]
@aanoaa 감사합니다. :)
