### ISSUE TITLE
주말(토/일) 미방문하는 봉사자의 통계 확인

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#74]
주말은 숙달되지 않은 인력으로 운영 중인 관계로 봉사자의 방문이 매우 중요합니다.
때문에 미방문하는 이유에 대해 다양한 방법으로 확인하고 있습니다. 
가장 높은 비율로 체크되는 이유 들에 대비책을 마련하려고 하는데요.

주말에 미방문하는 봉사자의 통계를 확인하고 싶습니다.
우선 미방문자의 신청서 답변 수와 비율을 확인하고자 합니다.

연령 | 신청서항목 1 | 신청서항목2 | 신청서 항목3 | 신청서 항목 4 | ... | 신청서 항목 끝
----|------------|------------|------------|-------------|----|-------------
AgeGroup -13|00|00|00|00|...|00
13-16|00|00|00|00|...|00
16-19|00|00|00|00|...|00
19-29|00|00|00|00|...|00
29+|00|00|00|00|...|00
합계|00|00|00|00|...|00

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1042

**Comment by 10001if** [comment]
이런 이슈는 보통 @yongbin  해주셨는데, 강의 중으로 바쁘실까봐 @keedi께도 함께 요청드립니다.

**Comment by yongbin** [comment]
```sql
     SELECT
       DAYNAME(a.`activity_from_date`) AS 'Weekday'
       ,b.gender                       AS 'Gender'
       ,YEAR(NOW()) - YEAR(b.birth_date) AS 'Age'
       ,IF( HOUR(activity_from_date) = 10 AND HOUR(activity_to_date) = 18, 'Full', IF(HOUR(activity_to_date) = 13, 'Morning', 'Afternoon')) AS 'Workhour'
       ,a.status  AS 'result'
       ,a.`path`
       ,a.`reason`
       ,a.`period`
       ,a.`job`
       ,a.`need_1365`
       ,a.`done_1365`
     FROM
       `volunteer_work` AS a INNER JOIN `volunteer` AS b ON a.volunteer_id = b.id
     WHERE
       a.status IN ( 'canceled', 'drop')
       AND HOUR(a.activity_from_date) IN (10,14)
       AND DAYNAME(a.`activity_from_date`) IN ('Sunday', 'Saturday')
       
```

중간결과를 @10001if 님께 전달드렸습니다.

**Comment by 10001if** [comment]
보내주신 자료로 체크하였습니다. 184명 중 134명 약 74% 정도가 136를 통해 유입되는 것으로 확인하였습니다. 136를 닫고 운영하면서 추이를 지켜보도록 하겠습니다.
