### ISSUE TITLE
1365 승인을 기다리는 봉사활동 방문자 목록의 재정렬

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#75]
![31bdf15dbc1889b4ff8a9962a3f0a89d](https://cloud.githubusercontent.com/assets/4696328/20474638/d00a5bea-b00a-11e6-9c10-09b161348700.png)

1365 승인을 기다리는 봉사활동 방문자 목록이 날짜순 & 시간 순으로 정렬되었으면 합니다.
14일 14시~18시
14일 10시~13시
13일 14시~18시

이렇게 있을 경우

14일 10시~13시
14일 14시~18시
13일 14시~18시
순으로 정렬되었으면 합니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1044

**Comment by aanoaa** [comment]
방문자 목록은 봉사활동에 관련된 이슈이지만 실제로는 재고관리에서 운영되므로
본래 이슈에서 다루도록 하겠습니다.
