### ISSUE TITLE
봉사자 소속센터 기록

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#76]
![40a9c4d7045b6cc05a4c58b367cf0d87](https://cloud.githubusercontent.com/assets/4696328/20474695/277d97c0-b00b-11e6-9b01-beb75158faff.png)

1365 시간 인증이 필요한 봉사자의 경우 봉사 신청서 작성 시 소속센터를 입력해주셔야 우리쪽에서 임의로 추가를 해서 시간을 넣어줄 수 있습니다.

봉사 신청서 작성 시 소속센터를 입력하는 양식을 추가하고자 합니다.

봉사희망지역(봉사센터) : 선택하세요(시/군) 선택하세요(구/군)

이때 봉사희망지역 정보를 모를 수 있으니, 본 사진을 띄워 보여주어야 합니다..

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1045

**Comment by aanoaa** [comment]
이해하지 못했습니다.

**Comment by aanoaa** [comment]
열린옷장에서 봉사활동을 했다면 당연히 `서울시 광진구` 아닌가요?

**Comment by aanoaa** [comment]
1365 인증기관 홈페이지에서 봉사활동을 마친 봉사자의 승인을 하기 위해
필요한 정보입니다.

**Comment by aanoaa** [comment]
1365 로그인 아이디로 검색할 순 없나요?

**Comment by MoDoLEE** [comment]
1365 프로그램에 리뉴얼 되면서 소속센터 입력이 필요 없어지고, 생년월일 입력이 필요해졌습니다.
`방문` 탭에서 보여지는 정보가 **아이디 | 소속센터** -> **아이디 | 생년월일** 로 변경되어야 합니다.
