### ISSUE TITLE
1월 1일 봉사 신청이 되지 않도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#78]
1월 1일에 봉사신청이 가능하게 되어 있습니다. 봉사 신청이 되지 않도록 요청드립니다~

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1089

**Comment by 10001if** [comment]
1월 1일에 봉사 활동 신청이 계속 들어 온다고 하네요~ 빠른 작업 요청드릴게요 ^^

**Comment by aanoaa** [comment]
my $hashref = $self->holidays(2016);

휴일목록을 가져올때에 연도를 받아서 처리하고 있습니다.
연도는 지금연도를 사용합니다.(now 의 연도 - 2016)

내년의 휴일까지 고려해야 한다면 now, now + 1 까지 되어야 하지 않나 싶습니다.
