### ISSUE TITLE
자원봉사 신청서의 모든 항목을 필수기재사항으로 변경 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#8]
하단에 주관식 질문 2가지만 빼놓고 남녀 성별부터 해당직업 선택까지 모두 필수 기재사항으로 변경 요청드립니다.
어제 변경한 이후로 접수가 들어오고 있는데요. 내용이 빠진 상태로 들어오는 것들이 많아서요. 변경 요청드립니다.

**Comment by aanoaa** [comment]
`checkbox` 는 아직 방법이 없습니다.

https://github.com/1000hz/bootstrap-validator/issues/122

서버쪽에서 에러를 발생시켜주어야 하겠습니다.
