### ISSUE TITLE
봉사자 생년월일 표시

### ISSUE THREAD

**Issue by ghost** [opencloset/volunteer#80]
1365 프로그램에 리뉴얼 되면서 소속센터 입력이 필요 없어지고, 생년월일 입력이 필요해졌습니다.
그래서 봉사활동 신청서에는 변경이 필요 없고, 다만 관리자 페이지에 표시되는 정보가 변경되어야 합니다.

관리자 페이지 내의 봉사활동 메뉴에서 `방문` 탭에서 보여지는 정보가
**아이디 | 소속센터** -> **아이디 | 생년월일** 로 변경되어야 합니다.

**Comment by aanoaa** [comment]
![2017-02-13 11-14-18](https://cloud.githubusercontent.com/assets/170528/22868840/95ebfbf2-f1dd-11e6-9dd6-bb5cad60cf16.png)

`1365 소속센터` 를 눌렀을때 소속센터를 확인할 수 있는 이미지도 필요없겠네요?

**Comment by aanoaa** [comment]
생년월일은 이미 입력받고 있습니다.
소속센터입력란을 제거하고 봉사활동 목록에서 소속센터 대신에 생년월일을 표시하겠습니다.

**Comment by ghost** [comment]
@aanoaa 넵. 이미지도 필요 없습니다.^^

**Comment by aanoaa** [comment]
신청서와 목록 모두 적용되었습니다.

**Comment by ghost** [comment]
확인했습니다. 감사합니다.
