### ISSUE TITLE
봉사활동 신청 페이지 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#82]
페이지1>열린옷장 자원봉사 신청 

- 매일매일 열린옷장 자원봉사 
- 매주 목요일 열린사진관 정기봉사 

페이지1-1> 매일매일 열린옷장 자원봉사 

- 요건 
17세 이상이라면 누구나! 
한 달 이내 최소 2회 활동 권장! 

- 활동내용
대여 의류 포장하기
의류 관리(다림질, 구두 닦기, 의류 정리 등)
기증/대여 메시지 입력 및 분류 작업
기증자/대여자를 위한 선물 만들기
# 위의 활동 중 상황에 따라 임의 배정 됩니다.  

- 신청하러 가기 

페이지 1-2> 신청하기 
- 정보입력
- 1365 승인 필요 여부 
체크 하면 id입력

-일자 및 시간 선택 
일자 선택 
시간 선택 
* 마감의 경우 정확히 고지
 
- 신청완료

페이지 1-3> 신청 완료
열린봉사자 신청이 완료 되었으며
승인 후 확인 문자 메시지가 발송됩니다. 

페이지 2-1> 열린 사진관 봉사활동 

- 매주 목요일 반짝! '열린 사진관' 
취준생의 이력서용 사진촬영비 대폭 인하 프로젝트!
취업준비생을 위한 활동에 함께해주세요. 

- 활동시간 : 매주 목요일 10시-18시
- 요건 : 한 달 이상 활동 가능하다면 누구나! 
- 활동장소 : 홍대 바라봄 사진관 
- 활동 내용 : 촬영 의류 준비 / 현장 관리
- 활동 혜택 : 한 달 이상 활동 시 증명사진 촬영 

- 신청하러 가기

페이지 2-2> 신청하기

-이름/핸드폰번호/나이/이메일/활동가능기간
-1365 승인 필요 여부
 id

페이지 2-3> 신청 완료 
열린사진관 봉상활동 신청이 완료 되었습니다!
담당자의 연락을 기다려주세요!

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1195

**Comment by aanoaa** [comment]
지금 소개페이지는 이미지로 대체되고 있습니다.
위 내용만 보고는 어디를 어떻게 바꿔야 할지 모르겠어요.

**Comment by 10001if** [comment]
이미지를 내리고 일일봉사와 열린사진관 봉사로 나눠 받으려 합니다.

**Comment by 10001if** [comment]
열린사진관 봉사도 함께 받으려하다보니 기존에 올라가 있는 이미지와 이원화 하기 힘들 것 같아. 잘 쓰시는 텍스트와 기호들로 표현하고자 합니다.

**Comment by aanoaa** [comment]
- **바라봄 사진관 봉사활동 신청도 받아서 관리해야한다.** 인가요?
- 위 내용이 들어간다면 디자인은 상관없나요?

-----------------------------------

신청서구조를 변경해야 합니다.
SMS 내용도 변경되어야 할 것 같습니다.(위치안내, 내용등)

관리측면에서 상태별 목록이 두개 필요해질 것 같습니다.

단순하게 봤을때 신청을 나눠서 받는 것 이외에는 고민한 내용이 없는 것 같습니다.

**Comment by 10001if** [comment]
네. 디자인은 관계없습니다. ^^ 그리고 바라봄 사진관 봉사자는 구글 독스 링크를 클릭하여 입력받는 방식으로 활용하려고 합니다. 장기적으로 계속 진행할지 여부를 아직은 판단하기가 힘듭니다.

**Comment by 10001if** [comment]
따라서 신청을 나눠서 받도록 진행하고 기존 절차는 그대로 두고 바라봄 사진관의 신청만 추가로 받도록 하려 합니다.

**Comment by aanoaa** [comment]
> 네. 디자인은 관계없습니다. ^^ 그리고 바라봄 사진관 봉사자는 구글 독스 링크를 클릭하여 입력받는 방식으로 활용하려고 합니다. 장기적으로 계속 진행할지 여부를 아직은 판단하기가 힘듭니다.

@10001if 구글독스의 링크가 필요합니다.

**Comment by 10001if** [comment]
https://docs.google.com/a/theopencloset.net/forms/d/e/1FAIpQLSfvPe98NYrqZuPmtFnbSZFld6u5Pc1_i7D4pZHj28r1MTmIcA/viewform
@aanoaa 적용 부탁드릴게요. ^^

**Comment by 10001if** [comment]
**_매일매일 
건대 열린옷장 자원봉사_**

요건

- 17세 이상이라면 누구나!
- 한 달 이내 최소 2회 활동 권장!

활동장소:  건대입구 열린옷장

활동내용 (아래 활동 중 상황에 따라 임의 배정 됩니다.)
- 대여 의류 포장하기
- 의류 관리(다림질, 구두 닦기, 의류 정리 등)
- 기증/대여 메시지 입력 및 분류 작업
- 기증자/대여자를 위한 선물 만들기

**Comment by 10001if** [comment]
**_매주 목요일 
홍대 열린사진관 자원봉사_**

매주 목요일 반짝! '열린 사진관'
취준생의 이력서용 사진촬영비 대폭 인하 프로젝트!
취업준비생을 위한 활동에 함께해주세요.

요건
**_- 한 달(주 1회, 총 4회)이상 활동 가능하다면 누구나!_**

활동장소:  홍대 바라봄 사진관
활동시간: 매주 목요일 10시 ~ 18시
활동내용: 촬영 의류 준비 / 현장 관리
활동혜택: 한 달 이상 활동 시 증명사진 촬영

**Comment by 10001if** [comment]
내용 수정 요청드릴게요. 볼드체와 기울임 표시가 수정된 내용입니다.

**Comment by 10001if** [comment]
![2017-03-09 9 08 22](https://cloud.githubusercontent.com/assets/4696328/23729944/1cf85442-04a8-11e7-96ff-f38025cb0bb5.png)
현재 상태입니다. 두 개의 높이가 서로 달라서요. 

매주 목요일 반짝! '열린 사진관'
취준생의 이력서용 사진촬영비 대폭 인하 프로젝트!
취업준비생을 위한 활동에 함께해주세요.

이 부분을 한 칸씩 띄우지 말고 보여주면 높이가 같아질까요? 높이가 동일하도록 수정 요청드립니다~

**Comment by aanoaa** [comment]
해상도의 차이 입니다
해상도와 상관없이 버튼위치가 같아져야 하겟네요

**Comment by 10001if** [comment]
@aanoaa 홍대 열린사진관 자원봉사 -> 열린사진관 자원봉사로 수정 요청드립니다. 다시 생각해 보니 장소가 있는데 굳이 다시 표기팔 필요가 없을 것 같아요.

**Comment by aanoaa** [comment]
> @10001if 10001if moved from 확인요망 to In Progress in 이슈 우선순위 3 hours ago

이거 급하다고 옮겨놓지 마세여
제가 당장 작업하는 이슈를 옮겨가면서 진행하겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
하단에 내용을 추가하려고 합니다. 링크 주소는 보이지 않고 문구를 클릭하면 새창으로 이동하도록 요청드립니다.

열린사진관의 상세내용이 궁금하다면? => http://blog.theopencloset.net/220693152487
닷페이스 열린사진관 현장영상 보기=> https://www.facebook.com/facespeakawake/videos/296703744020120/

**Comment by 10001if** [comment]
아직도 한 명도 신청하지 않았습니다. 조건을 조금 더 낮추어보고자 합니다. 요건 수정 요청드립니다.

요건
- 1회 이상 활동 가능하다면 누구나!

**Comment by 10001if** [comment]
@aanoaa 계속 신청이 들어오고 있지 않아서요. 요건과 자세한 내용 수정 요청드릴게요. 내일 오시면 바로 수정 부탁드릴게요. ^^

**Comment by 10001if** [comment]
봉사활동 신청 페이지의 좌우를 바꾸려고 합니다. 모바일의 경우에는 열린사진관 신청 내용이 보이지 않습니다. 조금이라도 노출량을 늘리기 위해 좌우 위치 수정을 요청드립니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
