### ISSUE TITLE
매주 일요일 오후는 봉사자 인원을 2명으로 수정하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#85]
현재는 3명입니다. 일요일 오후 봉사자는 인원 수를 1명 줄여 2명으로 운영하고자 합니다.

**Comment by aanoaa** [comment]
설정파일에서 일일 봉사자의 수를 컨트롤 할 수 있지만, 요일별 봉사자수를 컨트롤 할 수 는 없습니다.
작업이 필요합니다.

**Comment by 10001if** [comment]
@aanoaa 아.. 작업이 필요하군요. 작업량이 좀 되는 거라면 이야기 해주세요. 엄청 중요한 이슈는 아닙니다. 금방 해결될 것 같아서 올렸던 이슈입니다. ^^;

**Comment by aanoaa** [comment]
이슈 내용을 다시 읽어보니 요일 마다가 아니라, 요일의 오전/오후 시간대마다 관리가 필요한 것 입니다.

**Comment by aanoaa** [comment]
더 자세하게는 요일의 시간대마다 컨트롤 할 수 있어야 합니다.

봉사활동은 시간대 별로 신청을 받고 있습니다.
현재 신청 가능한 시간대는 아래와 같습니다.

- 10-13
- 10-18
- 14-18

최대인원이 4명이라는 뜻은 시간대별로 중첩된 봉사활동자 수가 4명씩 가능하다는 뜻 입니다.

    10시 ~ 11시에 4명까지 동시에 봉사활동이 가능
    11시 ~ 12시에 4명까지 동시에 봉사활동이 가능
    ...
    17시 ~ 18시에 4명까지 동시에 봉사활동이 가능

만약 `10-13` 에 4명, `14-18` 에 4명이 신청되었다면 `10-18` 은 신청을 할 수 없어야 합니다.
(`13-14` 에는 4명이 가능하지만 점심시간이라서 그렇게 신청을 받고 있지는 않습니다.)

일요일 오후에만 2명으로 제한하고 싶다면,

    일요일
    14시 ~ 15시에 2명까지 동시에 봉사활동이 가능
    15시 ~ 16시에 2명까지 동시에 봉사활동이 가능
    16시 ~ 17시에 2명까지 동시에 봉사활동이 가능
    17시 ~ 18시에 2명까지 동시에 봉사활동이 가능

하게끔 해야 합니다.
만약 `10-13` 에 0명, `14-18` 에 1명이 신청되었다면 `10-18` 은 1명 신청 가능합니다.
만약 `10-13` 에 0명, `14-18` 에 2명이 신청되었다면 `10-18` 은 0명 신청 가능합니다.

**Comment by aanoaa** [comment]
아직 예약이 열리지 않은 `2017-04-23` 일 부터 적용됩니다.
