### ISSUE TITLE
일요일 오전 봉사자 수를 2명으로 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#86]
일요일 오전 봉사자 수를 2명으로 변경하고자 합니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
#85 에서 요일별/시간대별로 신청인원을 조절하는 기능이 추가되었습니다.

**Comment by aanoaa** [comment]
설정파일을 수정하고 서비스 재시작 해주었습니다.

    # Monday is 1 ~ Sunday is 7
    max_volunteers => {
        default => 3,  # 모든 경우에 사용됨(요일/시간대가 지정되어 있지 않다면 default를 사용)
        7       => {   # Sun
            10 => 2,    # 10시는 2명
            11 => 2,    # 11시는 2명
            12 => 2,    # 12시는 2명
            13 => 2,    # 13시는 2명
            14 => 2,    # 14시는 2명
        },
    },

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
