### ISSUE TITLE
봉사신청 전일 오후 6시까지만 신청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#88]
전날 밤(열린옷장 퇴근 후)에 봉사신청을 해놓고 승인할 사이도 없이 방문을 하거나, 봉사 신청만 해놓고 방문하지 않는 경우가 생기고 있습니다. 전날 오후 6시전까지만 봉사 신청할 수 있도록 변경 부탁드립니다. 전날 밤에는 다음날로 봉사날짜를 선택할 수 없도록 하면 되지 않을까 싶습니다만,,,  @aanoaa 작업시간이 많이 걸릴까요? 간단한 작업이면 이슈우선순위에 올리겠습니다~

**Comment by aanoaa** [comment]
18:00 이후에는 익일(다음날) 봉사활동이 신청되지 않도록 해야 할까요?

**Comment by aanoaa** [comment]
맞다고 합니다.

**Comment by pingpongworks** [comment]
네 맞습니다^^

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
