### ISSUE TITLE
5월 1일과 5월 9일에 봉사 신청을 할 수 없도록 인원을 0명으로 조정함

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#89]
5월 1일은 노동절 휴일이고
5월 9일은 대선 임시 휴무일입니다.
양 일은 열린옷장이 운영되지 않으므로 봉사자 신청이 될 수 없도록 해야 합니다.
이미 신청한 분들에게는 안내 후 취소처리할 계획입니다.
추가로 신청이 들어오지 않도록 수정 요청드립니다.

**Comment by aanoaa** [comment]
반영하였습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
