### ISSUE TITLE
봉사활동 접수가 되면 이메일로 알림이 올 수 있도록 변경 

### ISSUE THREAD

**Issue by 10001if** [opencloset/volunteer#9]
접수 신청이 완료되면, info@theopencloset.net로 봉사신청이 들어왔다고 알려주는 이메일이 들어왔으면 좋겠습니다. 수시로 들어가서 확인하고는 있지만, 놓칠 가능성이 있는 것 같아서요.

**Comment by aanoaa** [comment]
따로 메일서버를 운영하지 않으니,

https://developers.google.com/gmail/api/v1/reference/users/messages/send

를 활용하도록 합니다.

**Comment by aanoaa** [comment]
https://developers.google.com/gmail/api/v1/reference/users/messages/send
https://developers.google.com/gmail/api/guides/uploads

**Comment by aanoaa** [comment]
```
400 Bad Request
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "failedPrecondition",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
```

이유를 모르겠습니다.

**Comment by aanoaa** [comment]
```
$ curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer $ACCESS_TOKEN' -d '{"raw":"RnJvbTogdm9sdW50ZWVyQHRoZW9wZW5jbG9zZXQubmV0DQpUbzogYWFub2FhQGdtYWlsLmNvbQ0KU3ViamVjdDogaGkNCkRhdGU6IEZyaSwgNCBTZXAgMjAxNSAxODoxMzoyMCArMDkwMA0KDQp0ZXN0DQo"}' https://www.googleapis.com/gmail/v1/users/volunteer@theopencloset.net/messages/send
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "failedPrecondition",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
```

`RnJvbTogdm9sdW50ZWVyQHRoZW9wZW5jbG9zZXQubmV0DQpUbzogYWFub2FhQGdtYWlsLmNvbQ0KU3ViamVjdDogaGkNCkRhdGU6IEZyaSwgNCBTZXAgMjAxNSAxODoxMzoyMCArMDkwMA0KDQp0ZXN0DQo` 을 decode 하면 아래와 같은 text
 가 나옵니다

```
From: volunteer@theopencloset.net
To: aanoaa@gmail.com
Subject: hi
Date: Fri, 4 Sep 2015 18:13:20 +0900

test

```

https://developers.google.com/gmail/api/v1/reference/users/messages/send#try-it 에서도 테스트 해보았고, 요청 메세지에는 문제가 없어 보입니다.
scope 문제가 아닌가 싶어서 `$ACCESS_TOKEN` 에 대한 유효성을 확인해보았습니다.

```
$ curl "https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=$ACCESS_TOKEN"
{
 "issued_to": "79843872170-upmktrk1lsa90v4r3jth6j3r0ul8o02i.apps.googleusercontent.com",
 "audience": "79843872170-upmktrk1lsa90v4r3jth6j3r0ul8o02i.apps.googleusercontent.com",
 "scope": "https://www.googleapis.com/auth/calendar https://mail.google.com/ https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/gmail.compose https://www.googleapis.com/auth/gmail.send",
 "expires_in": 3213,
 "access_type": "offline"
}
```

https://developers.google.com/gmail/api/v1/reference/users/messages/send#auth 에서 설명한,
- https://mail.google.com/
- https://www.googleapis.com/auth/gmail.modify
- https://www.googleapis.com/auth/gmail.compose
- https://www.googleapis.com/auth/gmail.send

4개의 scope 이 모두 포함되어 있습니다.

내부 메일서버를 운영하는 것을 생각해봐야 합니다.(cc @yongbin)

**Comment by aanoaa** [comment]
![screenshot-developers google com 2015-09-04 18-31-51](https://cloud.githubusercontent.com/assets/170528/9680664/4bf7a4aa-5333-11e5-9701-8443c34273d6.png)

https://developers.google.com/gmail/api/v1/reference/users/messages/send#try-it 에서 oauth 인증후에 테스트해본 결과입니다.

**Comment by aanoaa** [comment]
나는 왜 안되냐고

**Comment by aanoaa** [comment]
서버에서 동작함을 확인했습니다.

``` perl
use strict;
use warnings;
use Email::Simple;
use Email::Sender::Simple qw(sendmail);
use Email::Sender::Transport::SMTP qw();

my $transport = Email::Sender::Transport::SMTP->new( { host => 'localhost' } );
my $email = Email::Simple->create(
    header => [From => '<from>', To => '<to>', Subject => '<subject>'],
    body   => '<body>',
);

sendmail( $email, { transport => $transport } );
```
