### ISSUE TITLE
한달 이후까지 정기적으로 봉사 신청을 하려는 분들 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#91]
현재는 봉사신청을 한달 이후까지만 할 수가 있어서 
한달 이후까지 정기적으로 봉사를 하려는 분들이 신청을 하기가 조금 어렵습니다.
그렇다고 한달보다 더 많은 범위로 신청이 가능하도록 열어놓으면 
괜히 신청만 해놓고 안 오는 분들이 있을 수 있는 우려가 있습니다. 

**정기적으로 봉사를 하려는 분들이 한달 이후까지 신청할 수 있는 방법이 필요합니다.** 

제 생각에는 대여 방문예약을 '직원예약'으로 시간 상관없이 옷장지기가 할 수 있는 것처럼,
봉사예약도 기간 상관없이 옷장지기가 대신 해줄 수 있으면 어떨까 싶습니다. 

다른 아이디어가 있으시면 주셔도 좋습니다.

**Comment by aanoaa** [comment]
staff 계정으로 로그인해서 신청하면 신청가능일을 +1m 에서 +3m 으로 변경하면 될까요?
그게 꼭 +3m 일 필요도 없습니다. 기간을 정하지 않을 수도 있습니다.

**Comment by aanoaa** [comment]
배포하려다보니 

    public/thumbnails/

디렉토리가 volunteer 안에 있습니다.
avatar 에서 만드는 파일들이 왜 저기에..?

**Comment by aanoaa** [comment]
`ubic` 커맨드를 실행하는 `cwd` 에 영향을 받는게 아닐까 추측해봅니다.

**Comment by 10001if** [comment]
자원봉사자 중 정기봉사자의 조건을 설정해서 정기봉사자의 경우에는 기간 제한을 더 열어 직접 신청할 수 있도록 하는 것이 필요할 것 같습니다. 더 고민해 본 뒤 그때 이슈를 다시 열도록 하겠습니다. 감사합니다~
