### ISSUE TITLE
봉사자 신청 정원 조정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#93]
비수기가 도래함에 따라 봉사자 인원 조정이 필요합니다. 

현재는 동시간대 4명씩 신청이 가능합니다. 

    동시간대 3명씩 신청이 가능하도록 조정 부탁드립니다. 
    조정 기간 : 7월 현재 조정일~ 9월 30일

이미 4명씩 신청되어 있는 날짜들은 어쩔 수 없을 거 같습니다^^;;

**Comment by aanoaa** [comment]
> 조정 기간 : 7월 현재 조정일~ 9월 30일

특정 기간동안 n명씩 신청하게 하는 기능은 없습니다.
9월말에 다시 설정파일을 수정해서 이후부터 봉사활동인원을 조정해야 합니다.

**Comment by aanoaa** [comment]
# Monday is 1 ~ Sunday is 7
    max_volunteers => {
        default => 3,  # 모든 경우에 사용됨(요일/시간대가 지정되어 있지 않다면 default를 사용)
        7       => {   # Sun
            10 => 3,    # 10시는 3명
            11 => 3,    # 11시는 3명
            12 => 3,    # 12시는 3명
            13 => 3,    # 13시는 3명
            14 => 3,    # 14시는 3명
        },
    },

3명으로 변경하였습니다.

**Comment by pingpongworks** [comment]
네~ 감사요~

2017. 7. 4. 오후 4:43 Hyungsuk Hong <notifications@github.com> 작성:
