### ISSUE TITLE
#94 와 같은 경우 관리자가 수정 가능하도록

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#95]
봉사자의 정보를 관리자가 수정할 수 있으면 좋겠습니다. 

이름 오표기, 생년월일 오표기, 주소나 전화번호가 바뀐 경우 등

#94 같은 경우에 사용자정보처럼 봉사자 정보를 관리자가 수정 가능하면 좋겠습니다.

**Comment by aanoaa** [comment]
현재 수정기능에서는 

- 이름
- 생년월일
- email
- 전화번호

를 변경할 수 없습니다.

이것을 변경할 수 있도록 하게하고, 

- 활동시간

을 변경할 수 있는지 확인해봐야 합니다.

**Comment by pingpongworks** [comment]
현재는 필요하지 않은 내용이라 이슈 닫겠습니다.
