### ISSUE TITLE
열린사진관 봉사 신청 마감 공고

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#97]
![image](https://user-images.githubusercontent.com/17288038/28698731-3e7dbf84-7380-11e7-885b-ca2b13100463.png)

왼쪽의 열린사진관 자원봉사자 모집이 덕분에 매우 잘 이루어졌습니다. 

올해 봉사자는 더이상 모집할 수 없게 되어 
봉사자 모집 대신에 마감 공고를 올리려고 합니다.
아래와 같이 수정부탁드립니다.  

![- -1](https://user-images.githubusercontent.com/17288038/28699090-6955d24e-7382-11e7-89d9-df34b50eeded.gif)

**Comment by bentleypark** [comment]
@pingpongworks 소령님~ 봉사활동과련 소스코드를 찾아보니, 워드프레스 홈페이지의 내부소스가 아니고 외부코드라서 사일렉스에 도움을 요청을 해야할 것 같습니다.

**Comment by pingpongworks** [comment]
@Bentleypark 네~ 알겠습니다
@aanoaa 도와주셔야겠습니다~

**Comment by aanoaa** [comment]
저렇게 빈칸을 차지하게 두느니 예전처럼 화면 크게 바꾸는게 더 좋지 않나요?

**Comment by 10001if** [comment]
@aanoaa 열린사진관 봉사는 내리고 기존 자원봉사 화면을 크게 바꿔주세요. 봉사 마감 내용을 알려주고자 한 의도였는데, 여태까지 신청한 인원이 10명 이하이고 실제로 신청하고자 하는 인원이 많아 문의가 많다면 마감 내용을 안내해야겠지만, 그렇지 않아 그냥 내리는 것으로 결정했습니다.

**Comment by pingpongworks** [comment]
변경 확인했습니다. 감사합니다^^
