### ISSUE TITLE
알수없는 봉사신청 확인요망

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#98]
봉사자 신청 캘린더에 알 수 없는 신청들이 떠 있습니다. 
2017년 9월 8일부터 2018년 3월 27일까지 신청되어 있는 내역 확인이 필요합니다. 
구글캘린더 연동 문제가 아닌가 추측하고 있습니다만,
확인 부탁드립니다~

**Comment by aanoaa** [comment]
staff 계정으로 로그인하면 날짜 제한 없이 신청할 수 있습니다.
그렇게 신청된게 아닐까 싶은데..

**Comment by pingpongworks** [comment]
혹시 그렇게 신청된게 아닌지 옷장지기들에게 확인해보겠습니다. 아니라면 다른 가능성을 확인해봐야 하겠네요.

**Comment by aanoaa** [comment]
2017-11-18 이게 신청했던 이력중에 가장 먼 날인데 캘린더에 이상한 데이터가 들어가 있는 것 같네요.
확인해봐야 할 것 같습니다.

**Comment by aanoaa** [comment]
캘린더에 보이는게 많다고 해서 신청인원이 영향을 받는 것은 아닙니다.
캘린더에 날짜와 내용이 잘못들어가고 있다면 바로잡아야 하겠습니다.

**Comment by aanoaa** [comment]
2018-03-20, 2018-03-27 에 등록된 캘린더 이름으로 봉사활동 이력을 찾아봤습니다.
동일한 이름으로 2017-03-20, 2017-03-27 일 신청기록이 있습니다.

2017-04-22 에도 이력이 있는데 2018-04-22 캘린더에는 없습니다.

2018-03-27 <- 이게 마지막입니다.

초기에 프로그램 버그로 인해서 잘못 등록된 것 일 수도 있습니다.
캘린더에 쓰기 권한 있는 계정으로 이처럼 잘못된 데이터는 삭제하도록 하겠습니다.
이후에도 다시 발생한다면 현재 프로그램에 오류가 있는 것이니까 그때 살펴보겠습니다.

**Comment by aanoaa** [comment]
>  캘린더에 쓰기 권한 있는 계정으로 이처럼 잘못된 데이터는 삭제하도록 하겠습니다.

제가 계정정보를 모릅니다.
로그인 하셔서 캘린더에서 잘못된 이벤트를 삭제해주세요.

캘린더에서 삭제한다고 해서 봉사활동신청내역이 삭제되는 건 아니니까 의심되는 것들은 그냥 지우셔도 됩니다.

2017-03-27 이벤트가 마지막인 것 같습니다.

@pingpongworks @10001if

**Comment by pingpongworks** [comment]
말씀하신대로 지웠습니다~
