### ISSUE TITLE
봉사자 신청 인원 수정 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/volunteer#99]
비수기와 성수기의 봉사자 업무량 차이가 많이 나는데 비해
미리 대처를 하지 못해 봉사자들이 업무가 없어 난처한 상황이 발생하고 있습니다.

문제 해결을 위해, 비수기와 성수기를 미리 설정하고
필요한 봉사자 인원도 미리 제한할 수 있도록 하고자 합니다.

    비수기 : 1월, 7월, 8월
    성수기 : 나머지 기간

    비수기 봉사신청자 : 동시간대 2명
    성수기 봉사신청자 : 동시간대 4명

내년 1월까지 미리 설정해놓을 수 있다면 부탁드리고요,
아니면 일단
8월 비수기 인원, 9월부터 12월 성수기 인원 설정 부탁드릴게요~

당분간은 봉사인원 관련해서는 수정 없을 예정입니다~

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/1297 에서 옮겨왔습니다.

**Comment by aanoaa** [comment]
> 네~ 캘린더에 체크해놓고 인원조정 필요할 때마다 한달 전에 요청드리겠습니다.
> 
> 현시점은 비수기니까 동시간대 2명씩,
> 9월 7일부터는 동시간대 4명으로 조정부탁드립니다.

한달전에 요청한다는게 무슨 뜻인가요?
9/7일에 4명이면 8/7일부터 4명으로 해야 하는 건가요?

**Comment by pingpongworks** [comment]
9월 7일부터 4명이 신청가능하도록 되려면
한달전에 설정해놔야하는거 아닌가 생각했습니다. 
봉사자들은 한달전부터 신청이 가능하니까요. 


2017. 8. 9. 오후 3:26 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by aanoaa** [comment]
오늘을 기준으로 한달이내에 신청가능한 것 입니다.
기준을 4명으로 설정하면, 9월7일에 4명이 신청할 수 있지만 8월10일에도 4명이 신청할 수 있습니다.

**Comment by pingpongworks** [comment]
미리 설정할수는 없는거군요. 
그럼 이후로 동시간대 2명만 신청할 수 있게 설정 부탁드려요. 인원 조정이 필요할 때 다시 요청드릴게요~

2017. 8. 9. 오후 3:35 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by aanoaa** [comment]
2명으로 변경하였습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
